export interface AIModel {
  id: string;
  name: string;
  provider: string;
  category: string;
  capabilities: string[];
  deprecated?: boolean;
}

export const AI_MODELS: AIModel[] = [
  // Page 1 (1-24)
  { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Reasoning', 'Function calling'] },
  { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Reasoning', 'Efficiency'] },
  { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Large scale', 'Reasoning'] },
  { id: 'eleven-turbo-v2-5', name: 'Eleven Turbo v2.5', provider: 'ElevenLabs', category: 'Text-to-Speech', capabilities: ['Ultra-low latency'] },
  { id: 'eleven-flash-v2-5', name: 'Eleven Flash v2.5', provider: 'ElevenLabs', category: 'Text-to-Speech', capabilities: ['Fast'] },
  { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Balanced', 'Coding'] },
  { id: '@cf/moondream/moondream3.1-9B-A2B', name: 'Moondream 3.1', provider: 'moondream', category: 'Vision', capabilities: ['Compact vision'] },
  { id: 'nano-banana-2-lite', name: 'Nano Banana 2 Lite', provider: 'Google', category: 'Text-to-Image', capabilities: ['Fast', 'Compact'] },
  { id: 'seedance-2.0-mini', name: 'SeeDance 2.0 Mini', provider: 'ByteDance', category: 'Text-to-Video', capabilities: ['Fast clip'] },
  { id: 'hh1.1-r2v', name: 'HH 1.1 R2V', provider: 'Alibaba', category: 'Image-to-Video', capabilities: ['Reference to video'] },
  { id: 'hh1.1-i2v', name: 'HH 1.1 I2V', provider: 'Alibaba', category: 'Image-to-Video', capabilities: ['Image to video'] },
  { id: 'hh1.1-t2v', name: 'HH 1.1 T2V', provider: 'Alibaba', category: 'Text-to-Video', capabilities: ['High res'] },
  { id: 'p-video', name: 'P-Video', provider: 'Pruna AI', category: 'Text-to-Video', capabilities: ['Generative video'] },
  { id: 'p-video-animate', name: 'P-Video Animate', provider: 'Pruna AI', category: 'Image-to-Video', capabilities: ['Animation'] },
  { id: 'p-video-replace', name: 'P-Video Replace', provider: 'Pruna AI', category: 'Image-to-Video', capabilities: ['Substitution'] },
  { id: 'p-video-avatar', name: 'P-Video Avatar', provider: 'Pruna AI', category: 'Image-to-Video', capabilities: ['Avatar'] },
  { id: 'p-image-try-on', name: 'P-Image Try-On', provider: 'Pruna AI', category: 'Text-to-Image', capabilities: ['Virtual fitting'] },
  { id: 'p-image-upscale', name: 'P-Image Upscale', provider: 'Pruna AI', category: 'Text-to-Image', capabilities: ['Super resolution'] },
  { id: 'p-image-edit', name: 'P-Image Edit', provider: 'Pruna AI', category: 'Text-to-Image', capabilities: ['Editing'] },
  { id: 'p-image', name: 'P-Image', provider: 'Pruna AI', category: 'Text-to-Image', capabilities: ['Generative'] },
  { id: 'gemini-3.5-flash', name: 'Gemini 3.5 Flash', provider: 'Google', category: 'Text Generation', capabilities: ['Fast', 'Vision'] },
  { id: 'krea-2-large', name: 'Krea 2 Large', provider: 'krea', category: 'Text-to-Image', capabilities: ['Creative', 'HD'] },
  { id: 'krea-2-medium', name: 'Krea 2 Medium', provider: 'krea', category: 'Text-to-Image', capabilities: ['Balanced'] },
  { id: 'krea-2-medium-turbo', name: 'Krea 2 Medium Turbo', provider: 'krea', category: 'Text-to-Image', capabilities: ['Fast'] },

  // Page 2 (25-48)
  { id: 'aleph-2', name: 'Aleph-2', provider: 'RunwayML', category: 'Text-to-Video', capabilities: ['Artistic'] },
  { id: '@cf/zai-org/glm-5.2', name: 'GLM-5.2', provider: 'Zai', category: 'Text Generation', capabilities: ['Agentic', 'Tool calling'] },
  { id: '@cf/moonshotai/kimi-k2.7-code', name: 'Kimi k2.7 Code', provider: 'Moonshot AI', category: 'Text Generation', capabilities: ['Coding', 'Agentic'] },
  { id: 'claude-fable-5', name: 'Claude Fable 5', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Creative', 'Long context'] },
  { id: 'deepseek-v4-pro', name: 'DeepSeek v4 Pro', provider: 'DeepSeek', category: 'Text Generation', capabilities: ['Frontier', 'Code'] },
  { id: 'grok-voice', name: 'Grok Voice', provider: 'xAI', category: 'Text Generation', capabilities: ['Voice interactive'] },
  { id: 'grok-tts', name: 'Grok TTS', provider: 'xAI', category: 'Text-to-Speech', capabilities: ['Natural voice'] },
  { id: 'grok-stt', name: 'Grok STT', provider: 'xAI', category: 'Speech-to-Text', capabilities: ['Transcription'] },
  { id: 'grok-imagine-video-1.5-preview', name: 'Grok Imagine Video 1.5', provider: 'xAI', category: 'Image-to-Video', capabilities: ['Preview'] },
  { id: 'm3', name: 'M3', provider: 'MiniMax', category: 'Text Generation', capabilities: ['General purpose'] },
  { id: 'wan-2.7-i2v', name: 'Wan 2.7 I2V', provider: 'Alibaba', category: 'Image-to-Video', capabilities: ['HD animation'] },
  { id: 'claude-opus-4.8', name: 'Claude Opus 4.8', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Reasoning', 'Expert'] },
  { id: 'flux-2-pro-preview', name: 'Flux 2 Pro Preview', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Professional'] },
  { id: 'flux-2-max', name: 'Flux 2 Max', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Ultra-detail'] },
  { id: 'flux-2-flex', name: 'Flux 2 Flex', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Versatile'] },
  { id: 'grok-imagine-video', name: 'Grok Imagine Video', provider: 'xAI', category: 'Text-to-Video', capabilities: ['X native'] },
  { id: 'grok-imagine-image-quality', name: 'Grok Imagine Quality', provider: 'xAI', category: 'Text-to-Image', capabilities: ['High quality'] },
  { id: 'grok-4.3', name: 'Grok 4.3', provider: 'xAI', category: 'Text Generation', capabilities: ['Real-time', 'Social'] },
  { id: 'grok-imagine-image', name: 'Grok Imagine', provider: 'xAI', category: 'Text-to-Image', capabilities: ['Standard'] },
  { id: 'grok-4.20-multi-agent-0309', name: 'Grok 4.20 Multi-Agent', provider: 'xAI', category: 'Text Generation', capabilities: ['Multi-agent', 'Coordination'] },
  { id: 'grok-4.20-0309-non-reasoning', name: 'Grok 4.20 Non-Reasoning', provider: 'xAI', category: 'Text Generation', capabilities: ['Fast', 'Standard'] },
  { id: 'grok-4.20-0309-reasoning', name: 'Grok 4.20 Reasoning', provider: 'xAI', category: 'Text Generation', capabilities: ['Deep reasoning'] },
  { id: 'q3-pro', name: 'Q3 Pro', provider: 'Vidu', category: 'Text-to-Video', capabilities: ['Pro video'] },
  { id: 'q3-turbo', name: 'Q3 Turbo', provider: 'Vidu', category: 'Text-to-Video', capabilities: ['Fast video'] },

  // Page 3 (49-72)
  { id: 'gen-4.5', name: 'Gen-4.5', provider: 'RunwayML', category: 'Text-to-Video', capabilities: ['Frontier video'] },
  { id: 'recraftv4-vector', name: 'Recraft v4 Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Vector'] },
  { id: 'recraftv4-pro', name: 'Recraft v4 Pro', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Pro'] },
  { id: 'recraftv4-pro-vector', name: 'Recraft v4 Pro Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Pro vector'] },
  { id: 'recraftv4-1-vector', name: 'Recraft v4.1 Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Vector'] },
  { id: 'recraftv4-1-utility-vector', name: 'Recraft v4.1 Utility Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Utility'] },
  { id: 'recraftv4-1-utility-pro', name: 'Recraft v4.1 Utility Pro', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Utility pro'] },
  { id: 'recraftv4-1-utility-pro-vector', name: 'Recraft v4.1 Utility Pro Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Utility pro vector'] },
  { id: 'recraftv4-1-pro-vector', name: 'Recraft v4.1 Pro Vector', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Pro vector'] },
  { id: 'recraftv4-1-utility', name: 'Recraft v4.1 Utility', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Utility'] },
  { id: 'recraftv4-1', name: 'Recraft v4.1', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['General'] },
  { id: 'recraftv4-1-pro', name: 'Recraft v4.1 Pro', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Pro'] },
  { id: 'recraftv4', name: 'Recraft v4', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Standard'] },
  { id: 'v6', name: 'V6', provider: 'PixVerse', category: 'Text-to-Video', capabilities: ['High quality'] },
  { id: 'recraftv3', name: 'Recraft v3', provider: 'Recraft', category: 'Text-to-Image', capabilities: ['Legacy'] },
  { id: 'v5.6', name: 'V5.6', provider: 'PixVerse', category: 'Text-to-Video', capabilities: ['Balanced'] },
  { id: 'tts-1-hd', name: 'TTS 1 HD', provider: 'OpenAI', category: 'Text-to-Speech', capabilities: ['High definition'] },
  { id: 'tts-1', name: 'TTS 1', provider: 'OpenAI', category: 'Text-to-Speech', capabilities: ['Standard'] },
  { id: 'o4-mini', name: 'o4-mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Lightweight', 'Reasoning'] },
  { id: 'o3-mini', name: 'o3-mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Reasoning', 'Fast'] },
  { id: 'o3', name: 'o3', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Reasoning', 'Frontier'] },
  { id: 'gpt-image-2', name: 'GPT Image 2', provider: 'OpenAI', category: 'Text-to-Image', capabilities: ['DALL-E 3 next'] },
  { id: 'gpt-image-1.5', name: 'GPT Image 1.5', provider: 'OpenAI', category: 'Text-to-Image', capabilities: ['Optimized'] },
  { id: 'gpt-5.5-pro', name: 'GPT-5.5 Pro', provider: 'OpenAI', category: 'Text Generation', capabilities: ['High performance'] },

  // Page 4 (73-96)
  { id: 'gpt-5.5', name: 'GPT-5.5', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Next-gen'] },
  { id: 'gpt-5.4-nano', name: 'GPT-5.4 Nano', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Tiny', 'Fast'] },
  { id: 'gpt-5.4-pro', name: 'GPT-5.4 Pro', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Expert'] },
  { id: 'gpt-5.4', name: 'GPT-5.4', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Balanced'] },
  { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Compact'] },
  { id: 'gpt-5.1-chat', name: 'GPT-5.1 Chat', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Conversational'] },
  { id: 'gpt-5.1', name: 'GPT-5.1', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Foundation'] },
  { id: 'gpt-5-nano', name: 'GPT-5 Nano', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Mobile'] },
  { id: 'gpt-5-chat', name: 'GPT-5 Chat', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Chat'] },
  { id: 'gpt-5-mini', name: 'GPT-5 Mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Small'] },
  { id: 'gpt-5', name: 'GPT-5', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Frontier'] },
  { id: 'gpt-4o-transcribe', name: 'GPT-4o Transcribe', provider: 'OpenAI', category: 'Speech-to-Text', capabilities: ['Precise'] },
  { id: 'gpt-4o-mini', name: 'GPT-4o Mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Small', 'Fast'] },
  { id: 'gpt-4o', name: 'GPT-4o', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Vision', 'Fast'] },
  { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Optimized'] },
  { id: 'gpt-4.1-nano', name: 'GPT-4.1 Nano', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Fast'] },
  { id: 'gpt-4.1', name: 'GPT-4.1', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Improved'] },
  { id: 'speech-2.8-turbo', name: 'Speech 2.8 Turbo', provider: 'MiniMax', category: 'Text-to-Speech', capabilities: ['Fast'] },
  { id: 'music-2.6', name: 'Music 2.6', provider: 'MiniMax', category: 'Music Generation', capabilities: ['Composition'] },
  { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', provider: 'MiniMax', category: 'Text-to-Speech', capabilities: ['HD audio'] },
  { id: 'm2.7', name: 'M2.7', provider: 'MiniMax', category: 'Text Generation', capabilities: ['Standard'] },
  { id: 'hailuo-2.3-fast', name: 'Hailuo 2.3 Fast', provider: 'MiniMax', category: 'Text-to-Video', capabilities: ['Fast'] },
  { id: 'tts-2', name: 'TTS 2', provider: 'Inworld', category: 'Text-to-Speech', capabilities: ['Game ready'] },
  { id: 'hailuo-2.3', name: 'Hailuo 2.3', provider: 'MiniMax', category: 'Text-to-Video', capabilities: ['Standard'] },

  // Page 5 (97-120)
  { id: 'tts-1.5-max', name: 'TTS 1.5 Max', provider: 'Inworld', category: 'Text-to-Speech', capabilities: ['Quality'] },
  { id: 'tts-1.5-mini', name: 'TTS 1.5 Mini', provider: 'Inworld', category: 'Text-to-Speech', capabilities: ['Efficiency'] },
  { id: 'veo-3.1-fast', name: 'Veo 3.1 Fast', provider: 'Google', category: 'Text-to-Video', capabilities: ['Fast 4K'] },
  { id: 'veo-3-fast', name: 'Veo 3 Fast', provider: 'Google', category: 'Text-to-Video', capabilities: ['Standard fast'] },
  { id: 'veo-3.1', name: 'Veo 3.1', provider: 'Google', category: 'Text-to-Video', capabilities: ['4K quality'] },
  { id: 'nano-banana-pro', name: 'Nano Banana Pro', provider: 'Google', category: 'Text-to-Image', capabilities: ['Pro mobile'] },
  { id: 'veo-3', name: 'Veo 3', provider: 'Google', category: 'Text-to-Video', capabilities: ['Base quality'] },
  { id: 'nano-banana', name: 'Nano Banana', provider: 'Google', category: 'Text-to-Image', capabilities: ['Fast'] },
  { id: 'nano-banana-2', name: 'Nano Banana 2', provider: 'Google', category: 'Text-to-Image', capabilities: ['Standard'] },
  { id: 'gemini-3.1-pro', name: 'Gemini 3.1 Pro', provider: 'Google', category: 'Text Generation', capabilities: ['Reasoning', 'Vision'] },
  { id: 'imagen-4', name: 'Imagen 4', provider: 'Google', category: 'Text-to-Image', capabilities: ['HD', 'Realism'] },
  { id: 'gemini-3.1-flash-tts', name: 'Gemini 3.1 Flash TTS', provider: 'Google', category: 'Text-to-Speech', capabilities: ['Real-time'] },
  { id: 'gemini-3-flash', name: 'Gemini 3 Flash', provider: 'Google', category: 'Text Generation', capabilities: ['Fast'] },
  { id: 'gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash Lite', provider: 'Google', category: 'Text Generation', capabilities: ['Ultra-fast'] },
  { id: 'gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash Lite', provider: 'Google', category: 'Text Generation', capabilities: ['Efficient'] },
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', provider: 'Google', category: 'Text Generation', capabilities: ['Expert'] },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', provider: 'Google', category: 'Text Generation', capabilities: ['Standard Flash'] },
  { id: 'seedream-4.5', name: 'SeeDream 4.5', provider: 'ByteDance', category: 'Text-to-Image', capabilities: ['High fidelity'] },
  { id: 'seedream-5-lite', name: 'SeeDream 5 Lite', provider: 'ByteDance', category: 'Text-to-Image', capabilities: ['Lite'] },
  { id: 'seedream-4.0', name: 'SeeDream 4.0', provider: 'ByteDance', category: 'Text-to-Image', capabilities: ['Classic'] },
  { id: 'seedance-2.0-fast', name: 'SeeDance 2.0 Fast', provider: 'ByteDance', category: 'Text-to-Video', capabilities: ['Efficient'] },
  { id: 'universal-3-pro', name: 'Universal-3 Pro', provider: 'AssemblyAI', category: 'Speech-to-Text', capabilities: ['Robust'] },
  { id: 'seedance-2.0', name: 'SeeDance 2.0', provider: 'ByteDance', category: 'Text-to-Video', capabilities: ['Standard'] },
  { id: 'claude-sonnet-4.5', name: 'Claude Sonnet 4.5', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Balanced'] },

  // Page 6 (121-144)
  { id: 'claude-sonnet-4.6', name: 'Claude Sonnet 4.6', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Improved balanced'] },
  { id: 'claude-opus-4.6', name: 'Claude Opus 4.6', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Reasoning'] },
  { id: 'claude-opus-4.7', name: 'Claude Opus 4.7', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Improved reasoning'] },
  { id: 'claude-opus-4.5', name: 'Claude Opus 4.5', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Standard Opus'] },
  { id: 'claude-haiku-4.5', name: 'Claude Haiku 4.5', provider: 'Anthropic', category: 'Text Generation', capabilities: ['Fast'] },
  { id: 'wan-2.6-image', name: 'Wan 2.6 Image', provider: 'Alibaba', category: 'Text-to-Image', capabilities: ['Realistic'] },
  { id: 'qwen3-max', name: 'Qwen3 Max', provider: 'Alibaba', category: 'Text Generation', capabilities: ['Frontier', 'Multilingual'] },
  { id: 'qwen3.5-397b-a17b', name: 'Qwen3.5 397B', provider: 'Alibaba', category: 'Text Generation', capabilities: ['MoE', 'Massive scale'] },
  { id: 'hh1-t2v', name: 'HH 1 T2V', provider: 'Alibaba', category: 'Text-to-Video', capabilities: ['Legacy'] },
  { id: 'hh1-i2v', name: 'HH 1 I2V', provider: 'Alibaba', category: 'Image-to-Video', capabilities: ['Legacy'] },
  { id: '@cf/moonshotai/kimi-k2.6', name: 'Kimi k2.6', provider: 'Moonshot AI', category: 'Text Generation', capabilities: ['Long context', 'Vision'] },
  { id: '@cf/google/gemma-4-26b-a4b-it', name: 'Gemma 4 26B', provider: 'Google', category: 'Text Generation', capabilities: ['MoE', 'Reasoning'] },
  { id: '@cf/nvidia/nemotron-3-120b-a12b', name: 'Nemotron-3 120B', provider: 'NVIDIA', category: 'Text Generation', capabilities: ['MoE', 'Reasoning'] },
  { id: '@cf/zai-org/glm-4.7-flash', name: 'GLM-4.7 Flash', provider: 'Zai', category: 'Text Generation', capabilities: ['Fast', 'Function calling'] },
  { id: '@cf/black-forest-labs/flux-2-klein-9b', name: 'Flux 2 Klein 9B', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Fast', 'Efficient'] },
  { id: '@cf/black-forest-labs/flux-2-klein-4b', name: 'Flux 2 Klein 4B', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Edge', 'Ultra-fast'] },
  { id: '@cf/black-forest-labs/flux-2-dev', name: 'Flux 2 Dev', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Development'] },
  { id: '@cf/deepgram/aura-2-es', name: 'Aura 2 ES', provider: 'Deepgram', category: 'Text-to-Speech', capabilities: ['Spanish'] },
  { id: '@cf/deepgram/aura-2-en', name: 'Aura 2 EN', provider: 'Deepgram', category: 'Text-to-Speech', capabilities: ['English'] },
  { id: '@cf/ibm/granite-4.0-h-micro', name: 'Granite 4.0 Micro', provider: 'IBM', category: 'Text Generation', capabilities: ['Efficiency', 'Function calling'] },
  { id: '@cf/deepgram/flux', name: 'Flux Voice', provider: 'Deepgram', category: 'Speech-to-Text', capabilities: ['Real-time'] },
  { id: '@cf/pfnet/plamo-embedding-1b', name: 'Plamo Embedding 1B', provider: 'pfnet', category: 'Embeddings', capabilities: ['Japanese'] },
  { id: '@cf/aisingapore/gemma-sea-lion-v4-27b-it', name: 'Gemma SEA Lion v4', provider: 'aisingapore', category: 'Text Generation', capabilities: ['SEA Languages'] },
  { id: '@cf/ai4bharat/indictrans2-en-indic-1B', name: 'IndicTrans2 1B', provider: 'ai4bharat', category: 'Translation', capabilities: ['22 Indian languages'] },

  // Page 7 (145-168)
  { id: '@cf/baai/bge-reranker-base', name: 'BGE Reranker Base', provider: 'BAAI', category: 'Classification', capabilities: ['Re-ranking'] },
  { id: '@cf/meta/llama-guard-3-8b', name: 'Llama Guard 3 8B', provider: 'Meta', category: 'Text Generation', capabilities: ['Safety'] },
  { id: '@cf/deepseek/deepseek-r1-distill-qwen-32b', name: 'DeepSeek R1 Distill Qwen', provider: 'DeepSeek', category: 'Text Generation', capabilities: ['Reasoning'] },
  { id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast', name: 'Llama 3.3 70B Fast', provider: 'Meta', category: 'Text Generation', capabilities: ['Fast', 'Large scale'] },
  { id: '@cf/meta/llama-3.2-1b-instruct', name: 'Llama 3.2 1B', provider: 'Meta', category: 'Text Generation', capabilities: ['Edge'] },
  { id: '@cf/meta/llama-3.2-3b-instruct', name: 'Llama 3.2 3B', provider: 'Meta', category: 'Text Generation', capabilities: ['Efficient'] },
  { id: '@cf/meta/llama-3.2-11b-vision-instruct', name: 'Llama 3.2 11B Vision', provider: 'Meta', category: 'Text Generation', capabilities: ['Vision'] },
  { id: '@cf/black-forest-labs/flux-1-schnell', name: 'Flux 1 Schnell', provider: 'Black Forest Labs', category: 'Text-to-Image', capabilities: ['Fastest'] },
  { id: '@cf/meta/llama-3.1-8b-instruct-fp8', name: 'Llama 3.1 8B FP8', provider: 'Meta', category: 'Text Generation', capabilities: ['Optimized'] },
  { id: '@cf/myshell-ai/melotts', name: 'MeloTTS', provider: 'MyShell AI', category: 'Text-to-Speech', capabilities: ['Multilingual'] },
  { id: '@cf/google/embeddinggemma-300m', name: 'EmbeddingGemma 300M', provider: 'Google', category: 'Embeddings', capabilities: ['Multilingual'] },
  { id: '@cf/deepgram/aura-1', name: 'Aura 1', provider: 'Deepgram', category: 'Text-to-Speech', capabilities: ['Classic'] },
  { id: '@cf/leonardo/lucid-origin', name: 'Lucid Origin', provider: 'Leonardo', category: 'Text-to-Image', capabilities: ['Stylized'] },
  { id: '@cf/leonardo/phoenix-1.0', name: 'Phoenix 1.0', provider: 'Leonardo', category: 'Text-to-Image', capabilities: ['Classic'] },
  { id: '@cf/openai/gpt-oss-20b', name: 'GPT-OSS 20B', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Efficiency'] },
  { id: '@cf/openai/gpt-oss-120b', name: 'GPT-OSS 120B', provider: 'OpenAI', category: 'Text Generation', capabilities: ['Large scale'] },
  { id: '@cf/pipecat-ai/smart-turn-v2', name: 'Smart Turn v2', provider: 'Pipecat AI', category: 'Voice Detection', capabilities: ['Turn detection'] },
  { id: '@cf/qwen/qwen3-embedding-0.6b', name: 'Qwen3 Embedding', provider: 'Qwen', category: 'Embeddings', capabilities: ['High dim'] },
  { id: '@cf/deepgram/nova-3', name: 'Nova 3', provider: 'Deepgram', category: 'Speech-to-Text', capabilities: ['High accuracy'] },
  { id: '@cf/qwen/qwen3-30b-a3b-fp8', name: 'Qwen3 30B FP8', provider: 'Qwen', category: 'Text Generation', capabilities: ['MoE', 'Reasoning'] },
  { id: '@cf/meta/llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout 17B', provider: 'Meta', category: 'Text Generation', capabilities: ['MoE', 'Fast'] },
  { id: 'mistral-small-3.1-24b-instruct', name: 'Mistral Small 3.1', provider: 'Mistral AI', category: 'Text Generation', capabilities: ['Fast', 'Balanced'] },
  { id: '@cf/qwen/qwq-32b', name: 'QwQ 32B', provider: 'Qwen', category: 'Text Generation', capabilities: ['Reasoning'] },
  { id: '@cf/qwen/qwen2.5-coder-32b-instruct', name: 'Qwen2.5 Coder 32B', provider: 'Qwen', category: 'Text Generation', capabilities: ['Coding'] },

  // Page 8 (169-188)
  { id: '@cf/baai/bge-m3', name: 'BGE M3', provider: 'BAAI', category: 'Embeddings', capabilities: ['Multilingual'] },
  { id: '@cf/openai/whisper-large-v3-turbo', name: 'Whisper Large v3 Turbo', provider: 'OpenAI', category: 'Speech-to-Text', capabilities: ['Fast'] },
  { id: '@cf/llava-hf/llava-1.5-7b-hf', name: 'LLaVA 1.5 7B', provider: 'llava-hf', category: 'Vision', capabilities: ['Image analysis'] },
  { id: '@cf/openai/whisper-tiny-en', name: 'Whisper Tiny EN', provider: 'OpenAI', category: 'Speech-to-Text', capabilities: ['Lite'] },
  { id: '@cf/google/gemma-7b-it-lora', name: 'Gemma 7B LoRA', provider: 'Google', category: 'Text Generation', capabilities: ['LoRA', 'Fine-tuned'] },
  { id: '@cf/google/gemma-2b-it-lora', name: 'Gemma 2B LoRA', provider: 'Google', category: 'Text Generation', capabilities: ['LoRA', 'Edge'] },
  { id: '@cf/meta-llama/llama-2-7b-chat-hf-lora', name: 'Llama 2 7B LoRA', provider: 'meta-llama', category: 'Text Generation', capabilities: ['LoRA', 'Legacy'] },
  { id: '@cf/mistral/mistral-7b-instruct-v0.2-lora', name: 'Mistral 7B LoRA', provider: 'Mistral', category: 'Text Generation', capabilities: ['LoRA', 'Classic'] },
  { id: '@cf/bytedance/stable-diffusion-xl-lightning', name: 'SDXL Lightning', provider: 'ByteDance', category: 'Text-to-Image', capabilities: ['Turbo'] },
  { id: '@cf/lykon/dreamshaper-8-lcm', name: 'Dreamshaper 8 LCM', provider: 'lykon', category: 'Text-to-Image', capabilities: ['Fast'] },
  { id: '@cf/runwayml/stable-diffusion-v1-5-img2img', name: 'SD v1.5 Img2Img', provider: 'RunwayML', category: 'Text-to-Image', capabilities: ['Image-to-image'] },
  { id: '@cf/runwayml/stable-diffusion-v1-5-inpainting', name: 'SD v1.5 Inpainting', provider: 'RunwayML', category: 'Text-to-Image', capabilities: ['Inpainting'] },
  { id: '@cf/stabilityai/stable-diffusion-xl-base-1.0', name: 'SDXL Base 1.0', provider: 'Stability AI', category: 'Text-to-Image', capabilities: ['Base'] },
  { id: '@cf/baai/bge-small-en-v1.5', name: 'BGE Small EN v1.5', provider: 'BAAI', category: 'Embeddings', capabilities: ['Efficient'] },
  { id: '@cf/baai/bge-large-en-v1.5', name: 'BGE Large EN v1.5', provider: 'BAAI', category: 'Embeddings', capabilities: ['Accurate'] },
  { id: '@cf/huggingface/distilbert-sst-2-int8', name: 'DistilBERT SST-2', provider: 'Hugging Face', category: 'Classification', capabilities: ['Sentiment'] },
  { id: '@cf/openai/whisper', name: 'Whisper Base', provider: 'OpenAI', category: 'Speech-to-Text', capabilities: ['Classic'] },
  { id: '@cf/microsoft/resnet-50', name: 'ResNet 50', provider: 'Microsoft', category: 'Vision', capabilities: ['Classification'] },
  { id: '@cf/meta/m2m100-1.2b', name: 'M2M100 1.2B', provider: 'Meta', category: 'Translation', capabilities: ['Multilingual'] },
  { id: '@cf/baai/bge-base-en-v1.5', name: 'BGE Base EN v1.5', provider: 'BAAI', category: 'Embeddings', capabilities: ['Standard'] },
];

export const MODEL_CATEGORIES = Array.from(new Set(AI_MODELS.map(m => m.category)));
export const MODEL_PROVIDERS = Array.from(new Set(AI_MODELS.map(m => m.provider)));
