import {describe,it,expect,vi,afterEach} from 'vitest';
vi.mock('../src/core/azrail-sandbox',()=>({Sandbox:class{}}));
import worker from '../src/unified/entry';
import {sqliteD1} from './stubs/sqlite-d1';
import {createAccount,hashToken,requireResource} from '../src/lib/accounts';
import {unseal} from '../src/unified/connector-vault';
import {DEFAULT_DESIGN,contrast} from '../src/unified/design-contract';
import type {Env} from '../src/types';
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
const policy={id:'design',name:'Design workspace',url:'https://mcp.example.com/mcp',auth:'oauth',readTools:[],blockedTools:[],dailyCalls:10,oauth:{clientId:'registered-client',authorizationUrl:'https://auth.example.com/authorize',tokenUrl:'https://auth.example.com/token',scopes:['files:read']}};
async function fixture(){
 const {db,sqlite}=sqliteD1();const env={AZRAIL_D1:db,AZRAIL_R2:{list:async()=>({objects:[]})},AUTH_MODE:'oidc',PUBLIC_ORIGINS:'https://app.example.com',INTEGRATION_KEY:btoa('k'.repeat(32)),MCP_SERVERS:JSON.stringify([policy]),MCP_OAUTH_SECRETS:JSON.stringify({design:'server-client-secret'})} as unknown as Env;
 const alice=await createAccount(env,'Alice','editor'),bob=await createAccount(env,'Bob','editor');
 for(const [account,key] of [[alice,'a'],[bob,'b']] as const)await db.prepare('INSERT INTO web_sessions VALUES(?,?,?,?)').bind(await hashToken(key.repeat(64)),account.id,'https://app.example.com',Date.now()+3600000).run();
 const fetcher=vi.fn(async()=>Response.json({access_token:'oauth-private-token',token_type:'Bearer',expires_in:3600,refresh_token:'not-persisted'}));vi.stubGlobal('fetch',fetcher);
 const call=(path:string,body?:unknown,owner='a',method=body===undefined?'GET':'POST',state='',origin='https://app.example.com')=>worker.fetch(new Request(origin+path,{method,headers:{Cookie:`__Host-pulse-session=${owner.repeat(64)}; __Host-pulse-connector=${state}`,Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),env,{} as ExecutionContext);
 const start=async()=>{const response=await call('/api/connectors/oauth/start',{endpointKey:'design'});expect(response.status).toBe(200);const url=new URL((await response.json() as any).url);return {response,url,state:url.searchParams.get('state')!};};
 const finish=(state:string,owner='a',cookieState=state)=>call('/api/connectors/oauth/callback?code=provider-code&state='+state,undefined,owner,'GET',cookieState);
 return {env,sqlite,alice,bob,call,start,finish,fetcher};
}
describe('Connector OAuth boundary',()=>{
 it('binds the authorization code to PKCE, account, domain and exact resource',async()=>{
  const f=await fixture(),s=await f.start();expect(s.response.headers.get('Set-Cookie')).toMatch(/HttpOnly; Secure; SameSite=Lax/);
  expect(s.url.origin).toBe('https://auth.example.com');expect(s.url.searchParams.get('resource')).toBe(policy.url);expect(s.url.searchParams.get('redirect_uri')).toBe('https://app.example.com/api/connectors/oauth/callback');
  expect(s.url.href).not.toContain('server-client-secret');const row=f.sqlite.prepare('SELECT * FROM connector_oauth_states').get() as any;
  expect(row.state_hash).toBe(await hashToken(s.state));expect(row.verifier_cipher).not.toContain('provider-code');
  const pending=await unseal<{verifier:string}>(f.env,`oauth:${f.alice.id}:${row.state_hash}`,row.verifier_cipher);
  const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(pending.verifier));expect(s.url.searchParams.get('code_challenge')).toBe(Buffer.from(digest).toString('base64url'));
  const result=await f.finish(s.state);expect(result.status).toBe(303);expect(result.headers.get('Location')).toBe('/?connected=1');expect(result.headers.get('Set-Cookie')).toContain('Max-Age=0');
  const [target,options]=f.fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(target).toBe(policy.oauth.tokenUrl);expect(options.redirect).toBe('error');const body=options.body as URLSearchParams;expect(body.get('code_verifier')).toBe(pending.verifier);expect(body.get('resource')).toBe(policy.url);expect(body.get('client_secret')).toBe('server-client-secret');
  const connection=f.sqlite.prepare('SELECT * FROM connector_connections').get() as any;expect(connection.account_id).toBe(f.alice.id);expect(connection.secret_cipher).not.toContain('oauth-private-token');const secret=await unseal<any>(f.env,`connector:${f.alice.id}:${connection.id}`,connection.secret_cipher);expect(secret.token).toBe('oauth-private-token');expect(secret.refresh_token).toBeUndefined();expect(secret.expiresAt).toBeGreaterThan(Date.now());expect(await(await f.call('/api/connectors')).text()).not.toContain('oauth-private-token');
 });
 it('rejects a callback without the browser cookie without consuming a valid state',async()=>{const f=await fixture(),s=await f.start();expect((await f.finish(s.state,'a','')).status).toBe(400);expect(f.fetcher).not.toHaveBeenCalled();expect((await f.finish(s.state)).status).toBe(303);});
 it('rejects another account and prevents replay after the correct callback',async()=>{const f=await fixture(),s=await f.start();expect((await f.finish(s.state,'b')).status).toBe(400);expect(f.fetcher).not.toHaveBeenCalled();expect((await f.finish(s.state)).status).toBe(303);expect((await f.finish(s.state)).status).toBe(400);expect(f.fetcher).toHaveBeenCalledTimes(1);});
 it('rejects expired states before contacting the provider',async()=>{const f=await fixture(),s=await f.start();f.sqlite.exec('UPDATE connector_oauth_states SET expires_at=0');expect((await f.finish(s.state)).status).toBe(400);expect(f.fetcher).not.toHaveBeenCalled();});
 it('invalidates outstanding authorization after policy edits',async()=>{const f=await fixture(),s=await f.start();f.env.MCP_SERVERS=JSON.stringify([{...policy,dailyCalls:3}]);expect((await f.finish(s.state)).status).toBe(409);expect(f.fetcher).not.toHaveBeenCalled();});
 it('caps pending OAuth states without provider traffic',async()=>{const f=await fixture();for(let i=0;i<20;i++)await f.start();expect((await f.call('/api/connectors/oauth/start',{endpointKey:'design'})).status).toBe(429);expect(f.fetcher).not.toHaveBeenCalled();});
 it('blocks callbacks after the connection capacity has been reached',async()=>{const f=await fixture(),s=await f.start();for(let i=0;i<30;i++)f.sqlite.prepare('INSERT INTO connector_connections(id,account_id,endpoint_key,label,secret_cipher,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(`seed-${i}`,f.alice.id,'design','test','encrypted',0,0);expect((await f.finish(s.state)).status).toBe(429);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM connector_connections').get()?.n).toBe(30);});
 it('rejects malformed provider responses and consumes the code once',async()=>{const f=await fixture(),s=await f.start();f.fetcher.mockImplementationOnce(async()=>Response.json({access_token:{value:'wrong'},token_type:3}));expect((await f.finish(s.state)).status).toBe(502);expect((await f.finish(s.state)).status).toBe(400);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM connector_connections').get()?.n).toBe(0);});
 it('requires a reconnect for expired access tokens without a hidden refresh request',async()=>{const f=await fixture(),s=await f.start();f.fetcher.mockImplementationOnce(async()=>Response.json({access_token:'short-token',token_type:'Bearer',expires_in:.001}));expect((await f.finish(s.state)).status).toBe(303);const id=f.sqlite.prepare('SELECT id FROM connector_connections').get()?.id;vi.spyOn(Date,'now').mockReturnValue(Date.now()+10000);expect((await f.call(`/api/connectors/${id}/discover`,{})).status).toBe(401);expect(f.fetcher).toHaveBeenCalledTimes(1);});
});
describe('Project design contract',()=>{
 it('persists validated tokens, checks revisions and isolates project ownership',async()=>{const f=await fixture();await requireResource(f.env,f.alice,'project','project-style',true);const path='/api/studio/design-contract?projectId=project-style';const initial=await(await f.call(path)).json() as any;expect(initial).toEqual({revision:0,contract:DEFAULT_DESIGN});const contract={...DEFAULT_DESIGN,accent:'#c4b5fd',primaryAction:'Создать проект'};expect((await f.call(path,{baseRevision:0,contract},'a','PUT')).status).toBe(200);expect((await(await f.call(path)).json() as any).contract).toEqual(contract);expect((await f.call(path,{baseRevision:0,contract},'a','PUT')).status).toBe(409);expect((await f.call(path,undefined,'b')).status).toBe(404);expect((await f.call(path,{baseRevision:1,contract},'b','PUT')).status).toBe(404);expect((await f.call(path,{baseRevision:1,contract},'a','PUT')).status).toBe(200);});
 it('refuses inaccessible contrasts and missing error/offline states',async()=>{const f=await fixture();await requireResource(f.env,f.alice,'project','project-style',true);for(const change of [{text:'#0a0a0a'},{accent:'#0a0a0a'},{touchTarget:12},{reducedMotion:false},{requiredStates:['loading','success']}])expect((await f.call('/api/studio/design-contract?projectId=project-style',{baseRevision:0,contract:{...DEFAULT_DESIGN,...change}},'a','PUT')).status).toBe(400);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM project_design_contracts').get()?.n).toBe(0);expect(contrast('#ffffff','#000000')).toBeCloseTo(21);});
 it('does not silently overwrite concurrent design changes',async()=>{const f=await fixture();await requireResource(f.env,f.alice,'project','project-style',true);const results=await Promise.all([f.call('/api/studio/design-contract?projectId=project-style',{baseRevision:0,contract:DEFAULT_DESIGN},'a','PUT'),f.call('/api/studio/design-contract?projectId=project-style',{baseRevision:0,contract:{...DEFAULT_DESIGN,radius:4}},'a','PUT')]);expect(results.map(r=>r.status).sort()).toEqual([200,409]);});
});
