import {describe,it,expect,vi,afterEach} from 'vitest';
vi.mock('../src/core/azrail-sandbox',()=>({Sandbox:class{}}));
import worker from '../src/unified/entry';
import {sqliteD1} from './stubs/sqlite-d1';
import {createAccount,hashToken} from '../src/lib/accounts';
import {unseal} from '../src/unified/connector-vault';
import {connectorPolicies} from '../src/unified/connector-policy';
import {ExecutionEngine} from '../src/core/execution-engine';
import type {Env} from '../src/types';
afterEach(()=>vi.unstubAllGlobals());
const policy={id:'files',name:'Workspace files',url:'https://mcp.example.com/mcp',auth:'bearer',readTools:['search_files'],blockedTools:['destroy_all'],dailyCalls:20};
const tool=(name:string)=>({name,description:'Workspace file tool',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true}});
async function fixture(){const{db,sqlite}=sqliteD1();const env={AZRAIL_D1:db,AUTH_MODE:'oidc',PUBLIC_ORIGINS:'https://app.example.com',INTEGRATION_KEY:btoa('k'.repeat(32)),MCP_SERVERS:JSON.stringify([policy]),AZRAIL_R2:{list:async()=>({objects:[]})}} as unknown as Env;
 const alice=await createAccount(env,'Alice','editor'),bob=await createAccount(env,'Bob','editor');for(const [account,key]of [[alice,'a'],[bob,'b']]as const)sqlite.prepare('INSERT INTO web_sessions VALUES(?,?,?,?)').run(await hashToken(key.repeat(64)),account.id,'https://app.example.com',Date.now()+3600000);
 const methods:string[]=[];let catalog=[tool('search_files'),tool('write_file'),tool('destroy_all')],lose=false,sse=false;
 const fetcher=vi.fn(async(_url:any,init:any)=>{expect(String(_url)).toBe(policy.url);expect(init.redirect).toBe('error');expect(init.headers.Authorization).toBe('Bearer provider-secret');if(init.method==='DELETE')return new Response(null,{status:204});const m=JSON.parse(init.body);methods.push(m.method);if(m.method==='notifications/initialized')return new Response(null,{status:202});const result=m.method==='initialize'?{protocolVersion:'2025-11-25',capabilities:{tools:{}}}:m.method==='tools/list'?{tools:catalog}:{content:[{type:'text',text:'actual provider response'}]};if(m.method==='tools/call'&&lose)throw Error('Network disconnected after acceptance');const payload=JSON.stringify({jsonrpc:'2.0',id:m.id,result});if(sse&&m.method==='tools/call')return new Response(`: heartbeat\r\n\r\nevent: message\r\ndata: ${payload}\r\n\r\n`,{headers:{'Content-Type':'text/event-stream'}});return new Response(payload,{headers:{'Content-Type':'application/json',...(m.method==='initialize'?{'Mcp-Session-Id':'session-123'}:{})}});});vi.stubGlobal('fetch',fetcher);
 const call=(path:string,body?:unknown,owner='a',method=body===undefined?'GET':'POST',headers:Record<string,string>={})=>worker.fetch(new Request('https://app.example.com'+path,{method,headers:{Cookie:`__Host-pulse-session=${owner.repeat(64)}`,Origin:'https://app.example.com','Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)}),env,{}as ExecutionContext);
 const connect=async()=>{const r=await call('/api/connectors',{endpointKey:'files',token:'provider-secret'});expect(r.status).toBe(201);const {id}=await r.json()as any;expect((await call(`/api/connectors/${id}/discover`,{})).status).toBe(200);return id;};
 const prepare=async(id:string,name='write_file',key='prepare-request-0001',args:unknown={query:'hello'})=>call('/api/connectors/prepare',{connectionId:id,tool:name,arguments:args},'a','POST',{'Idempotency-Key':key});
 return{env,sqlite,alice,bob,methods,call,connect,prepare,fetcher,lose:()=>{lose=true;},useSSE:()=>{sse=true;},changeSchema:()=>{catalog=[...catalog,tool('new_tool')];}};
}
describe('Connector gateway isolation and durable effects',()=>{
 it('requires auth and rejects cross-origin mutations before outgoing calls',async()=>{const f=await fixture();expect((await worker.fetch(new Request('https://app.example.com/api/connectors'),f.env,{}as ExecutionContext)).status).toBe(401);expect((await f.call('/api/connectors',{},'a','POST',{Origin:'https://evil.example.com'})).status).toBe(403);expect(f.fetcher).not.toHaveBeenCalled();});
 it('encrypts provider token and binds ciphertext to account and connection',async()=>{const f=await fixture(),id=await f.connect();const row=f.sqlite.prepare('SELECT * FROM connector_connections WHERE id=?').get(id)as any;expect(row.secret_cipher).not.toContain('provider-secret');expect(await unseal(f.env,`connector:${f.alice.id}:${id}`,row.secret_cipher)).toEqual({token:'provider-secret'});await expect(unseal(f.env,`connector:${f.bob.id}:${id}`,row.secret_cipher)).rejects.toThrow();expect(await(await f.call('/api/connectors')).text()).not.toContain('provider-secret');});
 it('never exposes another account connection even to an operator',async()=>{const f=await fixture(),id=await f.connect();f.env.OPERATOR_ACCOUNT_IDS=f.bob.id;expect((await f.call(`/api/connectors/${id}/discover`,{},'b')).status).toBe(404);expect((await(await f.call('/api/connectors',undefined,'b')).json()as any).connections).toEqual([]);});
 it('ignores readOnlyHint from the remote server and requires exact confirmation',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;expect(p.approvalRequired).toBe(true);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{})).status).toBe(409);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(200);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(1);});
 it('does not execute twice under concurrent confirm or later replay',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;const r=await Promise.all([f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true}),f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})]);expect(r.map(x=>x.status).sort()).toEqual([200,409]);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(200);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(1);});
 it('conflicting arguments cannot reuse the same operation key',async()=>{const f=await fixture(),id=await f.connect();expect((await f.prepare(id)).status).toBe(201);expect((await f.prepare(id,'write_file','prepare-request-0001',{query:'other'})).status).toBe(409);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);});
 it('validates input against provider JSON Schema before preparation',async()=>{const f=await fixture(),id=await f.connect();expect((await f.prepare(id,'write_file','invalid-request-001',{query:7})).status).toBe(400);expect((await f.prepare(id,'write_file','invalid-request-002',{query:'hi',extra:true})).status).toBe(400);expect(f.sqlite.prepare('SELECT count(*) n FROM connector_calls').get()?.n).toBe(0);});
 it('retains an uncertain operation and reservation instead of replaying effects',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;f.lose();expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(1);expect(f.sqlite.prepare('SELECT status FROM connector_calls WHERE id=?').get(p.id)?.status).toBe('uncertain');expect(f.sqlite.prepare('SELECT status FROM resource_ledger WHERE id=?').get(p.id)?.status).toBe('uncertain');});
 it('rejects stale tool descriptions before remote execution',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;f.changeSchema();expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);});
 it('invalidates approval when policy changes',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;f.env.MCP_SERVERS=JSON.stringify([{...policy,dailyCalls:1}]);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);});
 it('supports Streamable HTTP SSE responses without executing returned text',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id,'search_files')).json()as any;f.useSSE();expect(p.approvalRequired).toBe(false);const r=await(await f.call(`/api/connectors/calls/${p.id}/execute`,{})).json()as any;expect(r.result.content[0].text).toBe('actual provider response');expect(r.status).toBe('succeeded');});
 it('cancelling a prepared call prevents any execution',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;expect((await f.call(`/api/connectors/calls/${p.id}/cancel`,{})).status).toBe(200);expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);});
 it('disconnect deletes credentials and cancels pending calls',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id)).json()as any;expect((await f.call(`/api/connectors/${id}`,undefined,'a','DELETE')).status).toBe(200);expect(f.sqlite.prepare('SELECT secret_cipher FROM connector_connections WHERE id=?').get(id)?.secret_cipher).toBe('');expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{confirm:true})).status).toBe(409);});
 it('honors the daily operation budget before dispatch',async()=>{const f=await fixture();f.env.MCP_SERVERS=JSON.stringify([{...policy,dailyCalls:1}]);const id=await f.connect(),p=await(await f.prepare(id,'search_files')).json()as any;expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{})).status).toBe(429);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);});
 it('preserves a durable result when ledger settlement temporarily fails',async()=>{const f=await fixture(),id=await f.connect(),p=await(await f.prepare(id,'search_files')).json()as any;const original=f.env.AZRAIL_D1.prepare.bind(f.env.AZRAIL_D1);let fail=true;vi.spyOn(f.env.AZRAIL_D1,'prepare').mockImplementation(sql=>{if(fail&&sql==='SELECT * FROM resource_ledger WHERE id=?'){fail=false;throw Error('ledger temporarily unavailable');}return original(sql);});const response=await(await f.call(`/api/connectors/calls/${p.id}/execute`,{})).json()as any;expect(response.status).toBe('succeeded');expect(response.ledgerPending).toBe(true);expect(f.sqlite.prepare('SELECT status FROM resource_ledger WHERE id=?').get(p.id)?.status).toBe('reserved');expect((await f.call(`/api/connectors/calls/${p.id}/execute`,{})).status).toBe(200);expect(f.sqlite.prepare('SELECT status FROM resource_ledger WHERE id=?').get(p.id)?.status).toBe('settled');expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(1);});
 it('atomically caps parallel connection creation',async()=>{const f=await fixture();for(let i=0;i<29;i++)f.sqlite.prepare('INSERT INTO connector_connections(id,account_id,endpoint_key,label,secret_cipher,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(`seed-${i}`,f.alice.id,'files','test','encrypted',0,0);const results=await Promise.all([f.call('/api/connectors',{endpointKey:'files',token:'provider-secret'}),f.call('/api/connectors',{endpointKey:'files',token:'provider-secret'})]);expect(results.map(r=>r.status).sort()).toEqual([201,429]);expect(f.sqlite.prepare('SELECT COUNT(*) n FROM connector_connections WHERE account_id=?').get(f.alice.id)?.n).toBe(30);});
 it('indexes at most five matching tools and hides blocked tools',async()=>{const f=await fixture();await f.connect();const r=await(await f.call('/api/connectors/tools?q=file')).json()as any;expect(r.tools.length).toBe(2);expect(r.tools.map((t:any)=>t.name)).not.toContain('destroy_all');expect((await(await f.call('/api/connectors/tools?q=file',undefined,'b')).json()as any).tools).toEqual([]);});
 it('agent uses server-derived project owner and cannot self-approve a write',async()=>{const f=await fixture(),id=await f.connect();f.sqlite.prepare('INSERT INTO resource_owners VALUES(?,?,?)').run('project','p1',f.alice.id);const engine=new ExecutionEngine(f.env);const ctx={missionId:'mission-test',projectId:'p1',iteration:0,maxIterations:2};const r=await engine.executeTool('connector_call',{connectionId:id,tool:'write_file',arguments:{query:'hi'},confirm:true,accountId:f.bob.id},ctx)as any;expect(r.approvalRequired).toBe(true);expect(f.methods.filter(m=>m==='tools/call')).toHaveLength(0);});
});
describe('Connector endpoint policy',()=>{
 it.each(['http://public.example.com/mcp','https://127.0.0.1/mcp','https://[::1]/mcp','https://a.internal/mcp','https://example.com/mcp?token=secret','https://user:pass@example.com/mcp','https://example.com:8080/mcp'])('rejects unsafe endpoint %s',(url)=>{expect(()=>connectorPolicies({MCP_SERVERS:JSON.stringify([{...policy,url}])}as Env)).toThrow();});
});
describe('Studio draft revisions',()=>{
 it('saves, reloads, rejects stale revision, and isolates another user',async()=>{const f=await fixture();const path='/api/studio/drafts/music';expect((await f.call(path,{baseRevision:0,values:{'studio-text':'Orbit',bpm:'124'}},'a','PUT')).status).toBe(200);expect((await(await f.call(path)).json()as any).values['studio-text']).toBe('Orbit');expect((await f.call(path,{baseRevision:0,values:{'studio-text':'overwrite'}},'a','PUT')).status).toBe(409);expect((await(await f.call(path,undefined,'b')).json()as any).revision).toBe(0);});
 it('refuses unknown secret fields',async()=>{const f=await fixture();expect((await f.call('/api/studio/drafts/music',{baseRevision:0,values:{token:'secret'}},'a','PUT')).status).toBe(400);});
});
