import {afterEach, describe, expect, it, vi} from 'vitest';
import {sqliteD1} from './stubs/sqlite-d1';
import {AccessError, createAccount, hashToken} from '../src/lib/accounts';
import {pluginRoute} from '../src/unified/plugins';
import {pluginCatalog, readProjectPlugins, requirePluginTool, selectedProjectSkills, validateManifest} from '../src/unified/plugin-policy';
import {canonical, seal} from '../src/unified/connector-vault';
import {connectorRoute, connectorResult, executeConnectorCall, prepareConnectorCall, searchConnectorTools} from '../src/unified/connectors';
import {ExecutionEngine} from '../src/core/execution-engine';
import type {Env} from '../src/types';

afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
const policy={id:'files',name:'Files',url:'https://mcp.example.com/mcp',auth:'bearer',readTools:['search_files'],blockedTools:['destroy_all'],dailyCalls:20};
const definitions=['search_files','write_file','destroy_all'].map(name=>({name,description:'Workspace tool',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false}}));
async function fixture(){
 const {db,sqlite}=sqliteD1();
 const env={AZRAIL_D1:db,AZRAIL_R2:{list:vi.fn(async()=>({objects:[]}))},AUTH_MODE:'oidc',PUBLIC_ORIGINS:'https://app.example.com',MCP_SERVERS:JSON.stringify([policy]),INTEGRATION_KEY:btoa('k'.repeat(32))} as unknown as Env;
 const alice=await createAccount(env,'Alice','editor'),bob=await createAccount(env,'Bob','editor'),viewer=await createAccount(env,'Viewer','viewer');
 for(const [account,key]of [[alice,'a'],[bob,'b'],[viewer,'c']]as const)sqlite.prepare('INSERT INTO web_sessions VALUES(?,?,?,?)').run(await hashToken(key.repeat(64)),account.id,'https://app.example.com',Date.now()+3600000);
 for(const [id,account]of [['p1',alice.id],['p2',alice.id],['p3',bob.id],['pv',viewer.id]])sqlite.prepare('INSERT INTO resource_owners VALUES(?,?,?)').run('project',id,account);
 async function connection(account=alice.id){const id=crypto.randomUUID();sqlite.prepare('INSERT INTO connector_connections(id,account_id,endpoint_key,label,secret_cipher,tools_json,tools_digest,verified_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,account,'files','Files',await seal(env,`connector:${account}:${id}`,{token:'hidden-provider-secret'}),JSON.stringify(definitions),await hashToken(canonical(definitions)),Date.now(),Date.now(),Date.now());return id;}
 async function call(path:string,body?:unknown,owner='a',method=body===undefined?'GET':'PUT'){
  try{const request=new Request('https://app.example.com'+path,{method,headers:{Cookie:`__Host-pulse-session=${owner.repeat(64)}`,Origin:'https://app.example.com','Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});return (await pluginRoute(request,env)??await connectorRoute(request,env))!;}catch(e){if(e instanceof AccessError)return Response.json({error:e.message},{status:e.status});throw e;}
 }
 const put=(plugins:unknown[],baseRevision=0,project='p1',owner='a')=>call(`/api/workbench/projects/${project}/plugins`,{baseRevision,plugins},owner);
 const install=(id:string,allowedTools=['search_files','write_file'])=>({id:'mcp:files',enabled:true,connectionIds:[id],allowedTools});
 const prepare=(id:string,tool='write_file',projectId='p1')=>prepareConnectorCall(env,alice.id,{connectionId:id,tool,arguments:{query:'hi'},projectId,idempotencyKey:crypto.randomUUID()});
 return {env,sqlite,alice,bob,call,put,connection,install,prepare};
}

describe('Project plugin manifests and configuration',()=>{
 it('catalog contains reviewed versioned workflows and approved connections without secrets',async()=>{const f=await fixture();await f.connection();await f.connection(f.bob.id);const response=await f.call('/api/plugins/catalog');const text=await response.text();expect(text).not.toContain('hidden-provider-secret');const catalog=JSON.parse(text);expect(catalog.plugins.map((p:any)=>p.id)).toEqual(['builtin.app-builder','builtin.code-review','builtin.release-check','mcp:files']);expect(catalog.connections).toHaveLength(1);expect(catalog.connections[0].tools.map((t:any)=>t.name)).toEqual(['search_files','write_file']);expect(catalog.plugins.every((p:any)=>p.manifestVersion===1&&p.version==='1.0.0')).toBe(true);});
 it('requires authentication and enforces ownership on reads and writes',async()=>{const f=await fixture();expect((await f.call('/api/plugins/catalog',undefined,'z')).status).toBe(401);expect((await f.call('/api/workbench/projects/p1/plugins',undefined,'b')).status).toBe(404);expect((await f.put([],0,'p1','b')).status).toBe(404);expect((await f.put([],0,'pv','c')).status).toBe(403);});
 it('preserves legacy behavior until an explicit policy is saved, including empty deny-all',async()=>{const f=await fixture();expect((await readProjectPlugins(f.env,'p1')).configured).toBe(false);await expect(requirePluginTool(f.env,'p1','write_file')).resolves.toBeUndefined();expect((await f.put([])).status).toBe(200);await expect(requirePluginTool(f.env,'p1','write_file')).rejects.toThrow('отключён');const engine=new ExecutionEngine(f.env);await expect(engine.executeTool('connector_search',{query:'file'},{missionId:'m1',projectId:'p1',iteration:0,maxIterations:2})).rejects.toThrow('отключён');expect(f.env.AZRAIL_R2.list).not.toHaveBeenCalled();});
 it('uses CAS for parallel creation and subsequent updates',async()=>{const f=await fixture();const responses=await Promise.all([f.put([{id:'builtin.app-builder',enabled:true}]),f.put([])]);expect(responses.map(r=>r.status).sort()).toEqual([200,409]);expect((await f.put([],0)).status).toBe(409);expect((await f.put([],1)).status).toBe(200);expect((await readProjectPlugins(f.env,'p1')).revision).toBe(2);});
 it('rejects unknown executable fields, capabilities and manifest versions',async()=>{const f=await fixture();for(const p of [{id:'builtin.app-builder',enabled:true,script:'fetch(secret)'},{id:'builtin.app-builder',enabled:true,allowedTools:['open_pr']},{id:'builtin.app-builder',enabled:true,version:'9.0.0'},{id:'builtin.unknown',enabled:true}])expect([400,409]).toContain((await f.put([p])).status);expect(()=>validateManifest({...pluginCatalog(f.env)[0],tools:['unknown_tool']})).toThrow();expect((await readProjectPlugins(f.env,'p1')).configured).toBe(false);});
 it('installs built-in tools with optional narrowing and supports disabling',async()=>{const f=await fixture();expect((await f.put([{id:'builtin.app-builder',enabled:true,allowedTools:['read_file']}])).status).toBe(200);await expect(requirePluginTool(f.env,'p1','read_file')).resolves.toBeUndefined();await expect(requirePluginTool(f.env,'p1','write_file')).rejects.toThrow();expect((await f.put([{id:'builtin.app-builder',enabled:false}],1)).status).toBe(200);await expect(requirePluginTool(f.env,'p1','read_file')).rejects.toThrow();});
 it('loads skills only when explicitly requested and installed',async()=>{const f=await fixture();expect(await selectedProjectSkills(f.env,'p1',undefined)).toBe('');await expect(selectedProjectSkills(f.env,'p1',['builtin.app-builder'])).rejects.toThrow();await f.put([{id:'builtin.app-builder',enabled:true}]);expect(await selectedProjectSkills(f.env,'p1',['builtin.app-builder'])).toContain('Изучи файлы');await expect(selectedProjectSkills(f.env,'p1',['mcp:files'])).rejects.toThrow();await f.put([{id:'builtin.app-builder',enabled:false}],1);await expect(selectedProjectSkills(f.env,'p1',['builtin.app-builder'])).rejects.toThrow();});
 it('does not turn malformed stored policy into legacy access',async()=>{const f=await fixture();await f.put([]);f.sqlite.exec("UPDATE project_plugin_policies SET plugins_json='not-json'");await expect(requirePluginTool(f.env,'p1','read_file')).rejects.toThrow('повреждена');});
});

describe('Project connector enforcement',()=>{
 it('rejects foreign connections, blocked tools, and implicit connector permissions',async()=>{const f=await fixture(),own=await f.connection(),foreign=await f.connection(f.bob.id);expect((await f.put([f.install(foreign)])).status).toBe(404);expect((await f.put([f.install(own,['destroy_all'])])).status).toBe(400);expect((await f.put([{id:'mcp:files',enabled:true,connectionIds:[own]}])).status).toBe(400);});
 it('filters discovery by selected connection and exact remote tool',async()=>{const f=await fixture(),one=await f.connection(),two=await f.connection();await f.put([f.install(one,['search_files'])]);const found=await searchConnectorTools(f.env,f.alice.id,'',5,'p1');expect(found.map(t=>[t.connectionId,t.name])).toEqual([[one,'search_files']]);await expect(f.prepare(two,'search_files')).rejects.toThrow('не разрешены');await expect(f.prepare(one,'write_file')).rejects.toThrow('не разрешены');});
 it('model cannot bypass scope, choose another account, or self-approve',async()=>{const f=await fixture(),one=await f.connection(),two=await f.connection();await f.put([f.install(one)]);const engine=new ExecutionEngine(f.env),ctx={missionId:'m1',projectId:'p1',iteration:0,maxIterations:2};await expect(engine.executeTool('connector_call',{connectionId:two,tool:'search_files',arguments:{query:'hi'},accountId:f.alice.id},ctx)).rejects.toThrow('не разрешены');const result=await engine.executeTool('connector_call',{connectionId:one,tool:'write_file',arguments:{query:'hi'},confirm:true,accountId:f.bob.id},ctx)as any;expect(result.approvalRequired).toBe(true);expect(result.projectId).toBe('p1');expect(f.sqlite.prepare('SELECT status FROM connector_calls').get()?.status).toBe('prepared');});
 it('revocation blocks already prepared calls before any remote fetch',async()=>{const f=await fixture(),id=await f.connection();await f.put([f.install(id)]);const prepared=await f.prepare(id);await f.put([],1);const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(executeConnectorCall(f.env,f.alice.id,prepared.id,true)).rejects.toThrow('не разрешены');expect(fetcher).not.toHaveBeenCalled();});
 it('policy revision changes invalidate outstanding approvals',async()=>{const f=await fixture(),id=await f.connection();await f.put([f.install(id)]);const prepared=await f.prepare(id);await f.put([f.install(id)],1);await expect(executeConnectorCall(f.env,f.alice.id,prepared.id,true)).rejects.toThrow('Плагины проекта изменились');});
 it('prevents using another project operation ID even under the same owner',async()=>{const f=await fixture(),id=await f.connection();await f.put([f.install(id)]);await f.put([f.install(id)],0,'p2');const prepared=await f.prepare(id);await expect(connectorResult(f.env,f.alice.id,prepared.id,'p2')).rejects.toThrow('другому проекту');});
 it('scopes manual tool preparation, search and history routes to the selected project',async()=>{const f=await fixture(),id=await f.connection();await f.put([f.install(id,['search_files'])]);const body={projectId:'p1',connectionId:id,tool:'write_file',arguments:{query:'hi'}};expect((await f.call('/api/connectors/prepare',body,'a','POST')).status).toBe(403);const prepared=await(await f.call('/api/connectors/prepare',{...body,tool:'search_files'},'a','POST')).json()as any;expect(prepared.projectId).toBe('p1');expect((await(await f.call('/api/connectors/calls?projectId=p1')).json()as any).calls.map((c:any)=>c.id)).toEqual([prepared.id]);expect((await(await f.call('/api/connectors/calls?projectId=p2')).json()as any).calls).toEqual([]);expect((await f.call('/api/connectors/calls/'+prepared.id+'?projectId=p2')).status).toBe(404);expect((await(await f.call('/api/connectors/tools?projectId=p1')).json()as any).tools.map((t:any)=>t.name)).toEqual(['search_files']);expect((await f.call('/api/connectors/tools?projectId=p1',undefined,'b')).status).toBe(404);});
 it('operator removal and disabled connections override a persisted grant',async()=>{const f=await fixture(),id=await f.connection();await f.put([f.install(id)]);f.env.MCP_SERVERS='[]';await expect(f.prepare(id)).rejects.toThrow('оператором');f.env.MCP_SERVERS=JSON.stringify([policy]);f.sqlite.prepare('UPDATE connector_connections SET disabled=1 WHERE id=?').run(id);await expect(f.prepare(id)).rejects.toThrow('недоступно');});
});
