import {it,expect,vi,afterEach} from 'vitest';
import {Window} from 'happy-dom';
import {readFileSync} from 'node:fs';
import {renderMission} from '../ui/mission-view';
import {mountStudioDraft} from '../ui/studio-draft';
afterEach(()=>vi.unstubAllGlobals());
const settle=async()=>{await new Promise(r=>setTimeout(r,0));await new Promise(r=>setTimeout(r,0));};
function documentWindow(){const w=new Window({url:'https://app.example.com'});w.document.write(readFileSync('ui/app.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));return w;}
it('shows actual plan progress and summary, keeping technical output collapsed and inert',()=>{const w=documentWindow(),d=w.document;renderMission(d as unknown as Document,{mission:{status:'executing'},plan:[{title:'Собрать проект',status:'done'},{title:'<script>steal()</script>',status:'doing'}],calls:[{tool:'write_file',status:'done'}],checks:[{passed:0}]});expect(d.getElementById('mission-progress')?.getAttribute('value')).toBe('1');expect(d.getElementById('mission-plan')?.querySelector('script')).toBeNull();expect(d.getElementById('mission-plan')?.textContent).toContain('<script>');expect(d.getElementById('mission-output')?.closest('details')?.open).toBe(false);expect(d.getElementById('mission-summary')?.textContent).not.toContain('"plan"');expect(d.getElementById('recover')?.hidden).toBe(true);renderMission(d as unknown as Document,{mission:{status:'failed'},result:{summary:'Проверка остановлена'}});expect(d.getElementById('recover')?.hidden).toBe(false);expect(d.getElementById('cancel')?.hidden).toBe(true);w.close();});
it('restores a server mission after reload without posting it again',async()=>{const w=documentWindow();w.requestIdleCallback=()=>0;w.HTMLElement.prototype.scrollIntoView=()=>{};w.sessionStorage.setItem('pulse.project','project-1');w.sessionStorage.setItem('pulse.mission','mission-1');const calls:string[]=[];w.fetch=(async(path:any,init:any={})=>{calls.push(`${init.method??'GET'} ${path}`);const data=path==='/auth/status'?{account:{id:'a',name:'A'}}:path==='/api/routing-settings'?{policy:{allowThirdPartyModels:false}}:{mission:{status:'completed'},result:{summary:'Сайт собран'}};return new w.Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});})as any;w.eval(readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)![1]);await settle();expect(w.document.getElementById('mission-panel')?.hidden).toBe(false);expect(w.document.getElementById('mission-summary')?.textContent).toBe('Сайт собран');expect(calls.some(c=>c.startsWith('POST '))).toBe(false);await w.happyDOM.abort();w.close();});
it('local projects show an explanation without requesting a backend',async()=>{const w=new Window({url:'file:///preview.html'});w.document.write(readFileSync('ui/app.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));w.requestIdleCallback=()=>0;w.HTMLElement.prototype.scrollIntoView=()=>{};const fetcher=vi.fn();w.fetch=fetcher;w.eval(readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)![1]);(w.document.querySelector('[data-view="projects"]')as any).click();expect(w.document.getElementById('project-list')?.textContent).toContain('после развёртывания');expect(fetcher).not.toHaveBeenCalled();await w.happyDOM.abort();w.close();});
it('studio undo/redo changes inputs, server conflict remains visible without forced overwrite',async()=>{const w=new Window();vi.stubGlobal('document',w.document);const host=w.document.createElement('div');host.innerHTML='<input id="studio-text" value="Initial">';w.document.body.append(host);const api=vi.fn(async(_path:string,options?:RequestInit)=>{if(options)throw Error('Черновик изменён в другой вкладке');return {revision:1,values:{'studio-text':'Saved'}};});const cleanup=mountStudioDraft(host as unknown as HTMLElement,'music',api,true);await settle();const field=host.querySelector('input')!;expect(field.value).toBe('Saved');field.value='Changed';field.dispatchEvent(new w.Event('input'));const buttons=Array.from(host.querySelectorAll('button'));buttons.find(b=>b.textContent==='↶ Отменить')!.click();expect(field.value).toBe('Saved');buttons.find(b=>b.textContent==='↷ Повторить')!.click();expect(field.value).toBe('Changed');buttons.find(b=>b.textContent==='Сохранить черновик')!.click();await settle();expect(host.querySelector('[role=status]')?.textContent).toContain('другой вкладке');expect(JSON.parse(String(api.mock.calls.at(-1)?.[1]?.body)).baseRevision).toBe(1);cleanup();w.close();});
it('keeps edits typed while an explicit draft reload is in flight',async()=>{
 const w=new Window();vi.stubGlobal('document',w.document);const host=w.document.createElement('div');host.innerHTML='<input id="studio-text" value="Initial">';w.document.body.append(host);
 let finish!:(value:any)=>void;const api=vi.fn().mockResolvedValueOnce({revision:1,values:{'studio-text':'Saved'}}).mockImplementationOnce(()=>new Promise(r=>{finish=r;})).mockResolvedValue({revision:3});
 const cleanup=mountStudioDraft(host as unknown as HTMLElement,'music',api,true);await settle();const field=host.querySelector('input')!,buttons=Array.from(host.querySelectorAll('button'));
 buttons.find(b=>b.textContent==='Загрузить сохранённый')!.click();field.value='New typing';field.dispatchEvent(new w.Event('input'));finish({revision:2,values:{'studio-text':'Other tab'}});await settle();expect(field.value).toBe('New typing');
 buttons.find(b=>b.textContent==='Сохранить черновик')!.click();await settle();expect(JSON.parse(String(api.mock.calls.at(-1)?.[1]?.body))).toEqual({baseRevision:2,values:{'studio-text':'New typing'}});cleanup();w.close();
});
it('does not display an unverified model check as passed, and names cancellation in progress',()=>{
 const w=documentWindow(),d=w.document;renderMission(d as unknown as Document,{mission:{status:'completed'},checks:[{passed:1}],events:[{type:'check.unverified'}]});expect(d.getElementById('mission-checks')?.textContent).not.toContain('пройдена');expect(d.getElementById('mission-checks')?.textContent).toContain('не подтверждена');
 renderMission(d as unknown as Document,{mission:{status:'cancelling'}});expect(d.getElementById('mission-status')?.textContent).toBe('Останавливаю задачу');w.close();
});
