import {it,expect,vi,afterEach} from 'vitest';
import {Window} from 'happy-dom';
import {readFileSync} from 'node:fs';
import {mountCode,mountPreview} from '../ui/project-code';
import {mountTools,mountModel} from '../ui/project-tools';
import {mountStudioDraft} from '../ui/studio-draft';
import {readRoute,routePath} from '../ui/navigation';
const windows:Window[]=[];
const settle=async()=>{for(let i=0;i<4;i++)await new Promise(r=>setTimeout(r,0));};
afterEach(async()=>{vi.unstubAllGlobals();for(const w of windows){await w.happyDOM.abort();w.close();}windows.length=0;});
function dom(){const w=new Window({url:'https://app.example.com'});windows.push(w);vi.stubGlobal('document',w.document);vi.stubGlobal('window',w);vi.stubGlobal('sessionStorage',w.sessionStorage);vi.stubGlobal('location',w.location);const host=w.document.createElement('section');w.document.body.append(host);return {w,host:host as unknown as HTMLElement};}
const click=(host:HTMLElement,text:string)=>([...host.querySelectorAll('button')].find(b=>b.textContent===text)!).click();
it('project URLs survive reload with explicit tabs and reject unknown tabs',()=>{expect(readRoute(new URL('https://a.test/projects/p-1/files'))).toEqual({page:'workbench',project:'p-1',tab:'files'});expect(readRoute(new URL('file:///a.html#/projects/p-1/memory'))).toEqual({page:'workbench',project:'p-1',tab:'memory'});expect(routePath({page:'workbench',project:'p-1',tab:'chat'})).toBe('/projects/p-1/chat');expect(readRoute(new URL('https://a.test/projects/p-1/fake'))).toEqual({page:'not-found'});});
it('editor preserves project/account scoped changes after a server conflict and navigation',async()=>{const {w,host}=dom();const api=vi.fn(async(path:string,options?:RequestInit)=>{if(path.includes('/artifacts'))return {artifacts:[]};if(options)throw Error('Версия проекта изменилась');if(path.endsWith('/files'))return {files:[{path:'index.html',size:10}],sourceDigest:'one'};return {path:'index.html',content:'Old',sourceDigest:'one'};});let cleanup=mountCode(host,'p','alice',api,true);await settle();click(host,'index.html');await settle();const editor=host.querySelector<HTMLTextAreaElement>('#file-editor')!;editor.value='<script>alert(1)</script>';editor.dispatchEvent(new w.Event('input') as unknown as Event);click(host,'Показать изменения');expect(host.querySelector('.code-diff script')).toBeNull();click(host,'Сохранить файл');await settle();expect(host.querySelector('[role=status]')?.textContent).toContain('изменилась');expect(JSON.parse(String(api.mock.calls.find(c=>c[1])?.[1]?.body))).toEqual({path:'index.html',content:'<script>alert(1)</script>',baseDigest:'one'});cleanup();host.replaceChildren();cleanup=mountCode(host,'p','alice',api,true);await settle();click(host,'index.html');await settle();expect(host.querySelector<HTMLTextAreaElement>('#file-editor')!.value).toContain('<script>');cleanup();host.replaceChildren();cleanup=mountCode(host,'p','bob',api,true);await settle();click(host,'index.html');await settle();expect(host.querySelector<HTMLTextAreaElement>('#file-editor')!.value).toBe('Old');cleanup();});
it('preview isolates project HTML and does not equate zero exit with verified tests',async()=>{const {host}=dom();const api=vi.fn(async(_path:string,options?:RequestInit)=>options?{available:true,exitCode:0,output:'no tests found',tests:{ok:false}}:{html:'<script>top.compromised=true</script><h1>Preview</h1>',warnings:[]});const cleanup=mountPreview(host,'p',api,true,'alice');await settle();expect(host.querySelector('iframe')?.getAttribute('sandbox')).toBe('');host.querySelector<HTMLInputElement>('#runtime-command')!.value='npm test';click(host,'Запустить проверку');await settle();expect(host.querySelector('pre')?.textContent).toContain('не подтверждена');expect((api.mock.calls.find(c=>c[1])?.[1]?.headers as Record<string,string>)['Idempotency-Key']).toBeTruthy();cleanup();});
it('plugin save sends exact project revision and explicitly selected connector tools',async()=>{const {host}=dom();const api=vi.fn(async(path:string,options?:RequestInit)=>{if(options)return {revision:3};if(path.includes('/catalog'))return {plugins:[{id:'mcp:github',name:'GitHub',description:'Repository tools',version:'1',kind:'connector',tools:[]}],connections:[{id:'c',endpointKey:'github',label:'My GitHub',tools:[{name:'read_file',risk:'read'},{name:'write_file',risk:'write'}]}]};return {configured:true,revision:2,plugins:[{id:'mcp:github',enabled:true,connectionIds:['c'],allowedTools:['read_file']}]};});const clean=mountTools(host,'project-a',api,true,()=>{});await settle();click(host,'Сохранить права');await settle();const call=api.mock.calls.find(c=>c[1]);expect(call?.[0]).toBe('/api/workbench/projects/project-a/plugins');expect(JSON.parse(String(call?.[1]?.body))).toEqual({baseRevision:2,plugins:[{id:'mcp:github',enabled:true,connectionIds:['c'],allowedTools:['read_file']}]});clean();});
it('model controls reflect actual supported efforts and server task limits',async()=>{const {host}=dom();const api=vi.fn(async(path:string)=>path.endsWith('/models')?{models:[{id:'astra',name:'Astra',available:false,unavailableReason:'Ключ не настроен',reasoningEfforts:['low','high']}],configuration:{maxIterations:20,defaultIterations:12,maxCostUsd:1}}:{revision:2,settings:{preferredModel:'astra',reasoningEffort:'high'}});const clean=mountModel(host,'p',api,true);await settle();expect([...host.querySelector<HTMLSelectElement>('#project-reasoning')!.options].map(o=>o.value)).toEqual(['','low','high']);expect(host.querySelector<HTMLInputElement>('#project-iterations')!.max).toBe('20');expect(host.textContent).toContain('Ключ не настроен');clean();});
it('draft endpoints and local caches stay tied to captured project scope',async()=>{const {w,host}=dom();host.innerHTML='<input id="studio-text" value="Start">';const api=vi.fn(async()=>({revision:0,values:{}}));let clean=mountStudioDraft(host,'image',api,true,{scope:'alice',projectId:'a'});await settle();const input=host.querySelector<HTMLInputElement>('input')!;input.value='Private A';input.dispatchEvent(new w.Event('input') as unknown as Event);clean();input.value='Start';clean=mountStudioDraft(host,'image',api,true,{scope:'alice',projectId:'b'});await settle();expect(input.value).toBe('Start');expect(api.mock.calls.map(c=>c[0])).toEqual(['/api/studio/drafts/image?projectId=a','/api/studio/drafts/image?projectId=b']);clean();});
function application(fetcher:(path:string,options:RequestInit)=>Promise<unknown>,url='https://app.example.com/',project='') {const w=new Window({url,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});windows.push(w);const html=readFileSync('index.html','utf8');w.document.write(html.replace(/<script>[\s\S]*?<\/script>/g,''));w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:https://app.example.com/artifact';w.URL.revokeObjectURL=()=>{};if(project)w.sessionStorage.setItem('pulse.project',project);w.fetch=(async(path:any,options:any={})=>{const result=await fetcher(String(path),options);return result instanceof Response?new w.Response(await result.arrayBuffer(),{status:result.status,headers:result.headers as any}):new w.Response(JSON.stringify(result),{headers:{'Content-Type':'application/json'}});}) as any;w.eval(html.match(/<script>([\s\S]*?)<\/script>/)![1]);return w;}
it('an attachment completed after creating another project never reaches its mission',async()=>{let finish!:(value:string)=>void;let missionBody:any;const w=application(async(path,options)=>{if(path==='/auth/status')return {account:{id:'alice',name:'Alice'},configured:true};if(path==='/api/routing-settings')return {policy:{allowThirdPartyModels:false}};if(path==='/api/workbench/projects'&&options.method==='POST')return {project:{id:'new',name:'New',revision:0,status:'active'}};if(path==='/api/workbench/projects/new')return {project:{id:'new',name:'New',revision:0,status:'active'}};if(path==='/api/mission'&&options.method==='POST'){missionBody=JSON.parse(String(options.body));return {missionId:'m'};}return {mission:{status:'completed'},result:{summary:'Done'},revision:0,values:{}};});await settle();const input=w.document.getElementById('attachments')!;Object.defineProperty(input,'files',{value:[{name:'secret.txt',size:20,text:()=>new Promise<string>(resolve=>{finish=resolve;})}]});input.dispatchEvent(new w.Event('change'));(w.document.getElementById('new-project') as any).click();await settle();(w.document.getElementById('project-create-name') as any).value='New';w.document.getElementById('project-create-form')!.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();finish('PRIVATE OLD PROJECT');await settle();(w.document.getElementById('prompt') as any).value='Build new';w.document.getElementById('composer')!.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();expect(missionBody.projectId).toBe('new');expect(missionBody.message).toBe('Build new');expect(w.document.getElementById('attachment-names')!.textContent).toBe('');});
it('saving an already generated image assigns its artifact without uploading another blob',async()=>{const calls:Array<{path:string;options:RequestInit}>=[];const w=application(async(path,options)=>{calls.push({path,options});if(path==='/auth/status')return {account:{id:'alice',name:'Alice'},configured:true};if(path==='/api/routing-settings')return {policy:{allowThirdPartyModels:false}};if(path==='/api/studio/image')return {id:'image-1',name:'image.png',url:'/api/studio/artifacts/image-1',projectId:null};if(path==='/api/studio/artifacts/image-1'&&options.method!=='PATCH')return new Response('png',{headers:{'Content-Type':'image/png'}});return {revision:0,values:{}};},'https://app.example.com/studios/image','project-a');await settle();(w.document.getElementById('studio-text') as any).value='Cover';(w.document.getElementById('studio-run') as any).click();await settle();const save=Array.from(w.document.querySelectorAll('#studio-result button')).find(b=>b.textContent==='Назначить текущему проекту') as any;expect(save).toBeTruthy();save.click();await settle();expect(calls.filter(c=>c.path==='/api/studio/artifacts'&&c.options.method==='POST')).toHaveLength(0);expect(JSON.parse(String(calls.find(c=>c.options.method==='PATCH')?.options.body))).toEqual({projectId:'project-a'});});

it('locks budget refresh and repeat saving until the write and its readback both finish',async()=>{
 const calls:Array<{path:string;options:RequestInit}>=[];
 let finishSave!:(value:unknown)=>void,finishReadback!:(value:unknown)=>void,committed=false;
 const pendingSave=new Promise(resolve=>{finishSave=resolve;}),pendingReadback=new Promise(resolve=>{finishReadback=resolve;});
 const initial={policy:{allowThirdPartyModels:false,monthlyBudgetUsd:10},committedUsd:0,workersPlan:'free'};
 const w=application(async(path,options)=>{
  calls.push({path,options});
  if(path==='/auth/status')return {account:{id:'operator',name:'Operator',operator:true},configured:true};
  if(path==='/api/admin/routing-settings'){await pendingSave;committed=true;return {ok:true};}
  if(path==='/api/routing-settings')return committed?pendingReadback:initial;
  if(path==='/api/workbench/models')return {models:[],configuration:{}};
  if(path==='/api/connectors')return {catalog:[],connections:[],vaultConfigured:false};
  if(path==='/api/studio/capabilities')return {image:false,sandbox:false};
  return {revision:0,values:{}};
 });
 await settle();(w.document.getElementById('settings') as any).click();await settle();
 const save=w.document.getElementById('save-mode') as unknown as HTMLButtonElement;
 const refresh=w.document.getElementById('refresh-limits') as unknown as HTMLButtonElement;
 const budget=w.document.getElementById('budget') as unknown as HTMLInputElement;
 const thirdParty=w.document.getElementById('third-party') as unknown as HTMLInputElement;
 const reads=()=>calls.filter(call=>call.path==='/api/routing-settings').length;
 const writes=()=>calls.filter(call=>call.path==='/api/admin/routing-settings');
 expect(save.disabled).toBe(false);budget.value='25';thirdParty.checked=true;
 const initialReads=reads();save.click();await settle();
 expect(writes()).toHaveLength(1);
 expect(JSON.parse(String(writes()[0].options.body))).toEqual({allowThirdPartyModels:true,monthlyBudgetUsd:25});
 for(const control of [save,refresh,budget,thirdParty])expect(control.disabled).toBe(true);
 refresh.click();save.click();await settle();
 expect(reads()).toBe(initialReads);expect(writes()).toHaveLength(1);
 finishSave({ok:true});await settle();
 expect(reads()).toBe(initialReads+1);
 for(const control of [save,refresh,budget,thirdParty])expect(control.disabled).toBe(true);
 refresh.click();save.click();await settle();
 expect(reads()).toBe(initialReads+1);expect(writes()).toHaveLength(1);
 finishReadback({...initial,policy:{allowThirdPartyModels:true,monthlyBudgetUsd:25}});await settle();
 for(const control of [save,refresh,budget,thirdParty])expect(control.disabled).toBe(false);
 expect(budget.value).toBe('25');expect(thirdParty.checked).toBe(true);
 expect(w.document.getElementById('notice-text')?.textContent).toBe('Настройки сохранены на сервере.');
});
