import { useEffect, useState } from 'react';
import { useUser } from '../../contexts/UserContext';
export default function BillingStudioPanel({ isLight }: { isLight: boolean }) {
  const { status, refreshStatus } = useUser();
  const [routing, setRouting] = useState<{externalEnabled: boolean; externalAvailable: boolean} | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { fetch('/api/models').then(async r => { const data = await r.json(); if (!r.ok) throw Error(data.error); setRouting(data); }).catch(e => setError(e.message)); }, []);
  const toggle = async () => {
    if (!routing || busy) return;
    if (!routing.externalEnabled && !window.confirm('Включить платные сторонние модели? Провайдер оплачивается отдельно. Дневной лимит ограничивает количество запросов, а не сумму счёта.')) return;
    setBusy(true); setError('');
    try { const r = await fetch('/api/admin/routing', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!routing.externalEnabled})}); const data = await r.json(); if(!r.ok) throw Error(data.error); setRouting({...routing,externalEnabled:data.externalEnabled}); }
    catch(e) {setError(e instanceof Error ? e.message : 'Ошибка настройки');} finally {setBusy(false);}
  };
  return <section className={`max-w-3xl rounded-2xl border p-6 ${isLight ? 'bg-white border-zinc-200 text-zinc-900' : 'bg-zinc-950/50 border-white/10 text-zinc-200'}`}><p className="text-xs text-violet-400 mb-3">ДОСТУП И РАСХОДЫ</p><h2 className="text-2xl mb-4">Рабочее пространство владельца</h2><p className="text-sm text-zinc-500 leading-7">Подписки для посетителей пока не подключены. Расходы Cloudflare и внешних провайдеров оплачиваются в их аккаунтах.</p><div className="my-6 rounded-xl border border-violet-400/20 p-5"><p className="text-sm">Осталось AI-запросов сегодня: <strong>{status?.remaining ?? '—'}</strong></p><p className="mt-2 text-xs text-zinc-500">Сброс лимита — 00:00 UTC. Один запрос роя может включать несколько обращений к моделям.</p><button onClick={refreshStatus} className="text-xs text-violet-400 mt-3">Обновить</button></div><div className="flex items-center justify-between gap-5"><div><h3 className="text-sm font-medium">Сторонние модели</h3><p className="text-xs text-zinc-500 mt-2">Включаются отдельно от Workers AI.</p></div><button role="switch" aria-checked={routing?.externalEnabled ?? false} aria-label="Сторонние модели" disabled={!routing || busy} onClick={toggle} className={`px-5 py-3 rounded-xl border ${routing?.externalEnabled ? 'bg-violet-500 text-white border-violet-500' : 'border-zinc-700'}`}>{routing?.externalEnabled ? 'Включены' : 'Выключены'}</button></div>{routing && !routing.externalAvailable && <p className="text-xs text-zinc-500 mt-4">Для включения владелец задаёт ключ провайдера и разрешение в настройках Worker.</p>}<p className="text-xs text-zinc-500 mt-6 leading-6">Выключенный режим блокирует вызовы внешних моделей. Использование Workers AI, R2 и других продуктов Cloudflare учитывается отдельно по вашему тарифу.</p>{error && <p role="alert" className="text-sm text-rose-300 mt-4">{error}</p>}</section>;
}
