import {toolForm} from './tool-form';
type API=(path:string,options?:RequestInit)=>Promise<any>;
const make=<K extends keyof HTMLElementTagNameMap>(tag:K,text='')=>{const el=document.createElement(tag);el.textContent=text;return el;};
export async function renderConnections(host:HTMLElement,api:API) {
 host.replaceChildren(make('p','Загружаю подключения…'));let requestKey=crypto.randomUUID();
 const status=make('p');status.className='context-note';status.setAttribute('role','status');
 const run=(fn:()=>Promise<void>)=>async()=>{try{await fn();}catch(e){status.textContent=e instanceof Error?e.message:'Не удалось выполнить действие';}};
 const button=(label:string,fn:()=>Promise<void>)=>{const b=make('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;await run(fn)();b.disabled=false;};return b;};
 const data=await api('/api/connectors');host.replaceChildren();
 host.append(make('p','Подключения принадлежат вашему аккаунту. Секреты хранятся на сервере. Внешние изменения показываются перед выполнением.'));
 if(!data.catalog.length){host.append(make('p','Оператор ещё не настроил доступные сервисы. Он появится здесь после подключения сервисов администратором.'));}
 else if(!data.vaultConfigured){host.append(make('p','Подключения недоступны: оператору нужно настроить защищённое хранилище.'));}
 else{
  const form=make('form');form.className='connector-form';const select=make('select');select.id='connector-service';const label=make('label','Сервис');label.htmlFor=select.id;
  for(const p of data.catalog){const o=make('option',p.name);o.value=p.id;select.append(o);}const token=make('input');token.id='connector-token';token.type='password';token.autocomplete='off';token.maxLength=8192;const tl=make('label','Токен сервиса');tl.htmlFor=token.id;
  const update=()=>{const needs=data.catalog.find((p:any)=>p.id===select.value)?.auth==='bearer';token.required=needs;token.hidden=!needs;tl.hidden=!needs;token.value='';};select.onchange=update;update();
  const submit=make('button','Подключить');submit.type='submit';submit.className='primary';form.append(label,select,tl,token,submit);form.onsubmit=e=>{e.preventDefault();submit.disabled=true;void run(async()=>{if(data.catalog.find((p:any)=>p.id===select.value)?.auth==='oauth'){const r=await api('/api/connectors/oauth/start',{method:'POST',body:JSON.stringify({endpointKey:select.value})});location.assign(r.url);return;}await api('/api/connectors',{method:'POST',body:JSON.stringify({endpointKey:select.value,token:token.value})});token.value='';await renderConnections(host,api);})().finally(()=>submit.disabled=false);};host.append(form);
 }
 const list=make('div');list.className='connector-list';host.append(list,status);
 for(const c of data.connections){const card=make('article');card.className='card';card.append(make('h3',c.label),make('p',c.verifiedAt?`Проверено · инструментов: ${c.toolCount}`:'Требуется проверка подключения'));const bar=make('div');bar.className='toolbar';bar.append(button('Проверить соединение',async()=>{const r=await api(`/api/connectors/${c.id}/discover`,{method:'POST',body:'{}'});status.textContent=`Соединение работает. Инструментов: ${r.tools.length}`;c.toolCount=r.tools.length;}));const remove=make('details');remove.append(make('summary','Отключить'));remove.append(make('p','Новые вызовы будут запрещены. Уже отправленная операция может завершиться.'),button('Подтвердить отключение',async()=>{await api(`/api/connectors/${c.id}`,{method:'DELETE'});await renderConnections(host,api);}));card.append(bar,remove);list.append(card);}
 const search=make('details');search.append(make('summary','Найти инструмент'));const query=make('input');query.placeholder='Например, поиск файлов';query.setAttribute('aria-label','Задача для поиска инструментов');const results=make('div');search.append(query,button('Найти',async()=>{const r=await api('/api/connectors/tools?q='+encodeURIComponent(query.value));results.replaceChildren();if(!r.tools.length)results.append(make('p','Нет подходящих инструментов. Проверьте подключение или измените запрос.'));for(const t of r.tools){const item=make('article');item.className='card';item.append(make('h3',`${t.connection} · ${t.name}`),make('p',t.description??''));const fields=make('div');const readArguments=toolForm(fields,t.inputSchema);
   const review=make('div');item.append(fields,button('Подготовить действие',async()=>{const args=readArguments();const call=await api('/api/connectors/prepare',{method:'POST',headers:{'Idempotency-Key':requestKey},body:JSON.stringify({connectionId:t.connectionId,tool:t.name,arguments:args})});requestKey=crypto.randomUUID();await showCall(review,call.id);}),review);results.append(item);}}),results);host.append(search);
 const history=make('details');history.append(make('summary','История и ожидающие действия'));const records=make('div');history.append(button('Обновить историю',async()=>{const r=await api('/api/connectors/calls');records.replaceChildren();for(const c of r.calls){const item=make('div');item.append(button(`${c.tool} · ${stateLabel(c.status)}`,async()=>{await showCall(item,c.id);}));records.append(item);}if(!r.calls.length)records.append(make('p','Внешних вызовов пока нет.'));}),records);host.append(history);
 async function showCall(target:HTMLElement,id:string){const c=await api(`/api/connectors/calls/${id}`);target.replaceChildren(make('h4',`${c.connectionLabel??c.connectionId} · ${c.tool}`),make('p',stateLabel(c.status)));const params=make('pre',JSON.stringify(c.arguments,null,2));target.append(params);if(c.status==='prepared'){target.append(make('p',c.approvalRequired?'Это внешнее действие. Проверьте сервис, инструмент и параметры. Сам сервис может применять собственные тарифы.':'Действие разрешено политикой чтения. Оно будет учтено в лимите подключений.'),button(c.approvalRequired?'Подтвердить и выполнить':'Выполнить чтение',async()=>{await api(`/api/connectors/calls/${id}/execute`,{method:'POST',body:JSON.stringify({confirm:true})});await showCall(target,id);}),button('Отменить действие',async()=>{await api(`/api/connectors/calls/${id}/cancel`,{method:'POST',body:'{}'});await showCall(target,id);}));}if(c.result)target.append(make('pre',JSON.stringify(c.result,null,2)));if(c.status==='uncertain'||c.status==='running')target.append(make('p','Повтор заблокирован. Проверьте результат в подключённом сервисе: операция могла выполниться.'));}
}
function stateLabel(status:string){return ({prepared:'ожидает действия',running:'отправлено',succeeded:'выполнено',failed:'ошибка',uncertain:'результат требует сверки',cancelled:'отменено'} as Record<string,string>)[status]??status;}
