export function download(blob:Blob,name:string){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function hash(s:string){let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;}
export function composeNotes(prompt:string,bpm:number,bars:number){
 let seed=hash(prompt),rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const scale=[53,55,56,58,60,61,63,65],notes:Array<{pitch:number;start:number;length:number;velocity:number}>=[];
 for(let i=0;i<bars*8;i++){if(rnd()>.23)notes.push({pitch:scale[Math.floor(rnd()*scale.length)],start:i*.5,length:rnd()>.6?.42:.22,velocity:.4+rnd()*.35});}
 return {notes,bpm,bars};
}
export async function renderMusic(prompt:string,bpm:number,bars:number){
 if(!Number.isFinite(bpm)||bpm<60||bpm>180||!Number.isInteger(bars)||bars<1||bars>16)throw Error('BPM 60–180, длина 1–16 тактов.');
 const song=composeNotes(prompt,bpm,bars),beat=60/bpm,duration=bars*4*beat+1;
 const ctx=new OfflineAudioContext(2,Math.ceil(duration*44100),44100);
 const master=ctx.createGain();master.gain.value=.32;master.connect(ctx.destination);
 for(const n of song.notes){const o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type='triangle';o.frequency.value=440*2**((n.pitch-69)/12);f.type='lowpass';f.frequency.value=1800;o.connect(f);f.connect(g);g.connect(master);const t=n.start*beat;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(n.velocity,t+.007);g.gain.exponentialRampToValueAtTime(.001,t+n.length*beat);o.start(t);o.stop(t+n.length*beat+.01);}
 for(let i=0;i<bars*4;i++){const t=i*beat,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(130,t);o.frequency.exponentialRampToValueAtTime(44,t+.12);g.gain.setValueAtTime(.85,t);g.gain.exponentialRampToValueAtTime(.001,t+.25);o.connect(g);g.connect(master);o.start(t);o.stop(t+.26);}
 for(let bar=0;bar<bars;bar++){const t=bar*4*beat,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=440*2**(([29,32,36,27][bar%4]-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.4,t+.02);g.gain.setValueAtTime(.4,t+3.7*beat);g.gain.linearRampToValueAtTime(0,t+4*beat);o.connect(g);g.connect(master);o.start(t);o.stop(t+4*beat);}
 const buffer=await ctx.startRendering();return {wav:wave(buffer),midi:midi(song),seconds:duration};
}
export function wave(buffer:AudioBuffer){const channels=buffer.numberOfChannels,n=buffer.length,bytes=new ArrayBuffer(44+n*channels*2),v=new DataView(bytes);const text=(p:number,s:string)=>[...s].forEach((c,i)=>v.setUint8(p+i,c.charCodeAt(0)));text(0,'RIFF');v.setUint32(4,bytes.byteLength-8,true);text(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,bytes.byteLength-44,true);const data=Array.from({length:channels},(_,c)=>buffer.getChannelData(c));for(let i=0;i<n;i++)for(let c=0;c<channels;c++){const x=Math.max(-1,Math.min(1,data[c][i]));v.setInt16(44+(i*channels+c)*2,x*(x<0?32768:32767),true);}return new Blob([bytes],{type:'audio/wav'});}
function midi(song:ReturnType<typeof composeNotes>){const events:Array<{t:number;bytes:number[]}>=[];for(const n of song.notes){events.push({t:Math.round(n.start*480),bytes:[0x90,n.pitch,Math.round(n.velocity*100)]},{t:Math.round((n.start+n.length)*480),bytes:[0x80,n.pitch,0]});}events.sort((a,b)=>a.t-b.t);const tempo=Math.round(60000000/song.bpm),data=[0,255,81,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255];let last=0;for(const e of events){let n=e.t-last;const delta=[n&127];while(n>>=7)delta.unshift((n&127)|128);data.push(...delta,...e.bytes);last=e.t;}data.push(0,255,47,0);const n=data.length;return new Blob([new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255,...data])],{type:'audio/midi'});}
export async function analyzeAudio(file:File,signal?:AbortSignal){if(file.size>30*1024*1024)throw Error('Аудиофайл должен быть меньше 30 МБ.');signal?.throwIfAborted();const ctx=new AudioContext();try{const buffer=await ctx.decodeAudioData(await file.arrayBuffer());signal?.throwIfAborted();const {measurePCM}=await import('./audio-analysis');return await measurePCM(Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),buffer.sampleRate,signal);}finally{await ctx.close();}}
export async function renderVideo(title:string,canvas:HTMLCanvasElement,signal:AbortSignal){
 if(!('MediaRecorder'in window)||!canvas.captureStream)throw Error('Этот браузер не поддерживает запись видео Canvas.');
 const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('Для WebM нужен браузер с поддержкой MediaRecorder.');
 canvas.width=1280;canvas.height=720;const ctx=canvas.getContext('2d')!,stream=canvas.captureStream(24),recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:2500000}),chunks:BlobPart[]=[];
 return new Promise<Blob>((resolve,reject)=>{let raf=0;const start=performance.now();function clean(){cancelAnimationFrame(raf);stream.getTracks().forEach(t=>t.stop());signal.removeEventListener('abort',abort);}function abort(){if(recorder.state!=='inactive')recorder.stop();clean();reject(Error('Запись остановлена'));}
 recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{clean();if(!signal.aborted)resolve(new Blob(chunks,{type:mime}));};recorder.onerror=()=>{clean();reject(Error('Ошибка записи видео'));};signal.addEventListener('abort',abort,{once:true});if(signal.aborted){abort();return;}
 const draw=()=>{const t=(performance.now()-start)/1000;ctx.fillStyle='#09090f';ctx.fillRect(0,0,1280,720);ctx.fillStyle='#8360b0';for(let i=0;i<18;i++){const height=40+150*(.5+.5*Math.sin(t*1.2+i*.55));ctx.globalAlpha=.3+.7*i/18;ctx.fillRect(810+i*20,360-height/2,5,height);}ctx.globalAlpha=1;ctx.fillStyle='#b8a0d2';ctx.font='18px sans-serif';ctx.fillText('MNMLL PULSE / ORIGINAL MOTION',75,120);ctx.fillStyle='#f0e9f7';ctx.font='600 52px Arial, sans-serif';const lines=title.match(/.{1,23}(?:\s|$)|.{1,23}/g)??['Моя идея'];lines.slice(0,4).forEach((line,i)=>ctx.fillText(line.trim(),75,315+i*65,610));ctx.font='17px sans-serif';ctx.fillStyle='#a38ab8';ctx.fillText('AZRAIL × PULSE',75,625);if(t>=8){recorder.stop();return;}raf=requestAnimationFrame(draw);};recorder.start();draw();
 });
}
