import {type API,button,field,node,status,projectAPI,errorText,localRead,localWrite} from './workbench-common';
export function mountChat(host:HTMLElement,id:string,accountId:string,api:API,writable:boolean):()=>void {
 let disposed=false,parentMessageId:string|undefined,submitting=false;const base=projectAPI(id),key=`pulse.chat.${accountId}.${id}`;host.dataset.panel='chat';const message=status(host),history=node('div','','chat-history');history.setAttribute('aria-label','Переписка проекта');const form=node('form','','chat-composer'),label=node('label','Сообщение'),input=node('textarea');input.id='chat-input';label.htmlFor=input.id;input.maxLength=20000;input.rows=4;input.placeholder='Обсудим идею, файлы или следующий шаг…';input.value=localRead<string>(key,'');input.oninput=()=>localWrite(key,input.value);const send=node('button','Отправить','primary');send.type='submit';send.disabled=!writable;const controls=node('div','','toolbar');controls.append(send,button('Обновить переписку',load));form.append(label,input,controls);host.append(node('h2','Чат проекта'),history,form);
 async function load(){const result=await api(`${base}/chat`);if(disposed)return;history.replaceChildren();for(const item of result.messages??[]){const article=node('article','',`chat-message ${item.role==='user'?'chat-user':''}`);article.append(node('small',item.role==='user'?'Вы':'AZRAIL'),node('p',item.content));if(item.model)article.append(node('small',item.model));if(item.role==='user'){article.append(button('Изменить и продолжить отсюда',()=>{input.value=item.content;parentMessageId=item.parent_message_id??undefined;localWrite(key,input.value);input.focus();message.textContent='Новый ответ создаст ветку разговора от выбранного сообщения.';}));}else article.append(button('Продолжить отсюда',()=>{parentMessageId=item.id;input.focus();message.textContent='Следующее сообщение продолжит выбранный ответ.';}));history.append(article);}if(!history.childElementCount)history.append(node('p','Здесь сохранится обсуждение этого проекта. Выполнение задачи с изменением файлов запускается во вкладке «Задача».','empty-state'));message.textContent='Переписка загружена.';}
 form.onsubmit=async event=>{event.preventDefault();if(submitting||!writable||!input.value.trim())return;const text=input.value;submitting=true;send.disabled=true;message.textContent='Ожидаю ответ. Запрос может продолжать работу после закрытия страницы.';try{const result=await api('/api/chat',{method:'POST',body:JSON.stringify({projectId:id,conversationId:id,message:text,...(parentMessageId?{parentMessageId}:{})})});if(disposed)return;if(result.result?.error)throw Error(result.result.error);if(input.value===text){input.value='';localWrite(key,'');}parentMessageId=result.assistantMessageId;await load();}catch(e){if(!disposed)message.textContent=errorText(e);}finally{submitting=false;if(!disposed)send.disabled=!writable;}};
 void load().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{localWrite(key,input.value);disposed=true;};
}
export function mountMemory(host:HTMLElement,id:string,api:API,writable:boolean):()=>void {
 let disposed=false;host.dataset.panel='memory';const path=`${projectAPI(id)}/memory`,message=status(host),list=node('div','','context-list'),key=field('Название факта','memory-key'),value=field('Значение','memory-value'),categoryLabel=node('label','Категория'),category=node('select');category.id='memory-category';categoryLabel.htmlFor=category.id;for(const [id,title] of [['preference','Предпочтение'],['architecture_decision','Архитектура'],['code_style','Стиль кода'],['tech_choice','Технология'],['known_issue','Известная проблема']]){const o=node('option',title);o.value=id;category.append(o);}categoryLabel.append(category);host.append(node('h2','Память проекта'),node('p','Факты доступны только этому проекту. Обновление проверяет предыдущую версию.','muted'),list,categoryLabel,key.wrap,value.wrap);
 async function load(){const result=await api(path);if(disposed)return;list.replaceChildren();for(const fact of result.facts??[]){const row=node('article','','card'),edit=field(fact.key,`memory-${fact.id}`,fact.value);edit.input.disabled=!writable;const save=button('Сохранить факт',async()=>{await api(path,{method:'PUT',body:JSON.stringify({category:fact.category,key:fact.key,value:edit.input.value,baseValue:fact.value})});await load();});const remove=button('Забыть',async()=>{await api(path,{method:'DELETE',body:JSON.stringify({category:fact.category,key:fact.key,baseValue:fact.value})});await load();});save.disabled=remove.disabled=!writable;row.append(node('small',fact.category),edit.wrap,save,remove);list.append(row);}if(!list.childElementCount)list.append(node('p','Сохранённых фактов пока нет.','empty-state'));message.textContent='Память загружена.';}
 const add=button('Добавить факт',async()=>{if(!key.input.value.trim()||!value.input.value.trim())throw Error('Заполните название и значение.');await api(path,{method:'PUT',body:JSON.stringify({category:category.value,key:key.input.value.trim(),value:value.input.value,baseValue:null})});key.input.value='';value.input.value='';await load();},'primary');add.disabled=!writable;host.append(add);void load().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;};
}
export function mountVersions(host:HTMLElement,id:string,api:API,writable:boolean):()=>void {
 let disposed=false,digest='';host.dataset.panel='versions';const path=projectAPI(id),message=status(host),list=node('div','','context-list'),summary=field('Описание версии','version-summary');host.append(node('h2','Версии проекта'),node('p','Снимок сохраняет полный набор файлов. Перед восстановлением создаётся резервная версия.','muted'),summary.wrap);
 async function load(){const [result,source]=await Promise.all([api(`${path}/versions`),api(`${path}/files`)]);if(disposed)return;digest=source.sourceDigest;list.replaceChildren();for(const version of result.versions??[]){const row=node('article','','card');row.append(node('h3',`Версия ${version.versionNumber}`),node('p',version.summary??''),node('small',version.createdAt??''));const restore=button('Восстановить',()=>{const confirmation=node('div','','confirm-action');confirmation.append(node('p','Текущие файлы будут заменены этой версией. Сервер сохранит резервную копию.'),button('Подтвердить восстановление',async()=>{await api(`${path}/versions/${encodeURIComponent(version.id)}/restore`,{method:'POST',body:JSON.stringify({baseDigest:digest})});await load();message.textContent='Версия восстановлена. Обновите открытые файлы перед следующей записью.';}),button('Отмена',()=>confirmation.remove()));row.append(confirmation);});restore.disabled=!writable||!version.restorable;row.append(restore);if(!version.restorable)row.append(node('p','Старая версия: полный снимок файлов отсутствует.','muted'));list.append(row);}if(!list.childElementCount)list.append(node('p','Создайте первый снимок перед большой правкой.','empty-state'));message.textContent='Версии загружены.';}
 const save=button('Создать версию',async()=>{await api(`${path}/versions`,{method:'POST',body:JSON.stringify({baseDigest:digest,summary:summary.input.value})});await load();message.textContent='Версия сохранена.';},'primary');save.disabled=!writable;host.append(save,button('Обновить',load),list);void load().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;};
}
