import {type API,button,field,node,status,projectAPI,errorText,localRead,localWrite} from './workbench-common';
interface FileEntry{path:string;size:number;uploaded?:boolean;}
interface Edit{content:string;baseDigest:string;original:string;}
export function mountCode(host:HTMLElement,id:string,accountId:string,api:API,writable:boolean):()=>void {
 const path=projectAPI(id),key=`pulse.editor.${accountId}.${id}`;let disposed=false,request=0,current='',digest='',original='',files:FileEntry[]=[];
 const drafts=localRead<Record<string,Edit>>(key,{});host.dataset.panel='code';
 const message=status(host),tools=node('div','','toolbar'),search=field('Поиск файлов','file-search'),newPath=field('Путь нового файла','file-new-path');
 newPath.input.placeholder='src/app.ts';tools.append(search.wrap,newPath.wrap);
 const workspace=node('div','','code-workspace'),tree=node('nav','','file-tree');tree.setAttribute('aria-label','Файлы проекта');
 const body=node('div','','code-body'),title=node('h2','Выберите файл'),editor=node('textarea','','code-editor');editor.id='file-editor';editor.spellcheck=false;editor.setAttribute('aria-label','Содержимое файла');editor.disabled=true;
 const actions=node('div','','toolbar'),diff=node('pre','','code-diff');diff.hidden=true;diff.setAttribute('aria-label','Изменения файла');
 const persist=()=>{if(current&&!editor.disabled){if(editor.value!==original)drafts[current]={content:editor.value,baseDigest:drafts[current]?.baseDigest??digest,original};else delete drafts[current];localWrite(key,drafts);}};
 const renderDiff=()=>{diff.replaceChildren();const before=original.split('\n'),after=editor.value.split('\n');for(let n=0;n<Math.max(before.length,after.length);n++){if(before[n]===after[n]){diff.append(node('span',`  ${after[n]??''}\n`));continue;}if(n<before.length)diff.append(node('span',`− ${before[n]}\n`,'diff-remove'));if(n<after.length)diff.append(node('span',`+ ${after[n]}\n`,'diff-add'));}};
 editor.oninput=()=>{persist();message.textContent='Правки сохранены в этой вкладке. «Сохранить файл» запишет их в проект.';if(!diff.hidden)renderDiff();};
 async function open(filePath:string){persist();const token=++request;message.textContent='Загружаю файл…';const result=await api(`${path}/file?path=${encodeURIComponent(filePath)}`);if(disposed||token!==request)return;current=result.path;digest=result.sourceDigest;const draft=drafts[current];original=draft?.original??result.content;editor.value=draft?.content??result.content;title.textContent=current;editor.disabled=!writable;message.textContent=draft?(draft.baseDigest!==digest?'Версия проекта изменилась. Ваш черновик сохранён. Сравните его с серверной копией перед записью.':'Восстановлены несохранённые правки.'):'Файл загружен.';save.disabled=!writable;rename.disabled=!writable;remove.disabled=!writable;renderTree();if(!diff.hidden)renderDiff();}
 function renderTree(){tree.replaceChildren();const query=search.input.value.toLowerCase();for(const file of files.filter(f=>f.path.toLowerCase().includes(query))){const b=button(file.path,()=>open(file.path));b.className='file-entry';b.style.paddingLeft=`${12+Math.min(file.path.split('/').length-1,6)*10}px`;b.setAttribute('aria-current',String(current===file.path));b.title=`${file.path} · ${file.size} байт`;tree.append(b);}if(!tree.childElementCount)tree.append(node('p',files.length?'Нет совпадений':'В проекте пока нет файлов.','muted'));}
 async function refresh(){const result=await api(`${path}/files`);if(disposed)return;files=result.files;digest=result.sourceDigest;renderTree();message.textContent=files.length?`${files.length} файлов в проекте`:'Создайте файл или поставьте задачу агенту во вкладке «Задача».';}
 const save=button('Сохранить файл',async()=>{persist();const captured=current,text=editor.value;const result=await api(`${path}/file`,{method:'PUT',body:JSON.stringify({path:captured,content:text,baseDigest:drafts[captured]?.baseDigest??digest})});delete drafts[captured];localWrite(key,drafts);if(disposed)return;if(current===captured){original=text;digest=result.sourceDigest;persist();}message.textContent='Файл сохранён на сервере.';await refresh();},'primary');save.disabled=true;
 const renameField=field('Новое имя / путь','file-rename-path');renameField.input.placeholder='src/renamed.ts';
 const rename=button('Переименовать',async()=>{if(editor.value!==original)throw Error('Сначала сохраните правки файла.');const result=await api(`${path}/rename`,{method:'POST',body:JSON.stringify({path:current,newPath:renameField.input.value,baseDigest:digest})});await refresh();await open(result.path);});rename.disabled=true;
 const remove=button('Удалить файл',async()=>{const captured=current;const confirmation=node('div','','confirm-action');confirmation.append(node('p',`Удалить ${captured} из проекта? Несохранённые правки останутся в этой вкладке.`),button('Подтвердить удаление',async()=>{await api(`${path}/file`,{method:'DELETE',body:JSON.stringify({path:captured,baseDigest:digest})});confirmation.remove();if(disposed)return;current='';editor.value='';editor.disabled=true;title.textContent='Выберите файл';await refresh();}),button('Отмена',()=>confirmation.remove()));body.append(confirmation);});remove.disabled=true;
 actions.append(save,button('Показать изменения',()=>{diff.hidden=!diff.hidden;renderDiff();}),button('Прочитать серверную копию',async()=>{if(!current)return;const result=await api(`${path}/file?path=${encodeURIComponent(current)}`);if(disposed)return;const compare=node('details');compare.open=true;compare.append(node('summary','Текущая серверная копия'),node('pre',result.content));body.append(compare);message.textContent='Черновик сохранён. После сравнения можно принять эту версию как основу для своих правок.';compare.append(button('Сохранить мои правки поверх этой версии',()=>{if(current!==result.path)throw Error('Сначала откройте файл, для которого показано сравнение.');original=result.content;digest=result.sourceDigest;drafts[current]={content:editor.value,baseDigest:digest,original};localWrite(key,drafts);renderDiff();compare.remove();message.textContent='Основа обновлена. Нажмите «Сохранить файл», чтобы записать проверенные правки.';}));}),remove);
 tools.append(button('Создать файл',async()=>{if(!writable)throw Error('Доступен только просмотр.');const name=newPath.input.value.trim();if(!name)throw Error('Введите путь файла.');if(files.some(f=>f.path===name))throw Error('Файл уже существует.');await api(`${path}/file`,{method:'PUT',body:JSON.stringify({path:name,content:'',baseDigest:digest})});await refresh();await open(name);}),button('Обновить список',refresh));
 const more=node('details');more.append(node('summary','Переименование'),renameField.wrap,rename);body.append(title,editor,actions,diff,more);workspace.append(tree,body);host.append(tools,workspace);const artifacts=node('div','','cards');host.append(node('h2','Результаты студий'),artifacts);void api(`/api/studio/artifacts?projectId=${encodeURIComponent(id)}`).then(result=>{if(disposed)return;for(const artifact of result.artifacts??[]){const card=node('a',artifact.name,'card');card.href=`/api/studio/artifacts/${encodeURIComponent(artifact.id)}`;card.download=artifact.name;card.append(node('small',`${artifact.mime} · ${artifact.bytes} байт`));artifacts.append(card);}if(!artifacts.childElementCount)artifacts.append(node('p','Сохранённые результаты студий появятся здесь.','muted'));}).catch(e=>{if(!disposed)artifacts.textContent=errorText(e);});search.input.oninput=renderTree;void refresh().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{persist();disposed=true;request++;};
}
export function mountPreview(host:HTMLElement,id:string,api:API,writable:boolean,accountId='local'):()=>void {
 let disposed=false;host.dataset.panel='preview';const path=projectAPI(id),message=status(host),tools=node('div','','toolbar'),frame=node('iframe','','project-preview');frame.title='Статический предпросмотр проекта';frame.setAttribute('sandbox','');frame.referrerPolicy='no-referrer';
 for(const [title,width] of [['Телефон','390px'],['Планшет','768px'],['Компьютер','100%']])tools.append(button(title,()=>{frame.style.width=width;}));
 async function refresh(){message.textContent='Собираю статический предпросмотр…';const result=await api(`${path}/preview`);if(disposed)return;frame.srcdoc=result.html;message.textContent=['Статический просмотр: скрипты выключены.',...(result.warnings??[])].join(' ');}
 tools.append(button('Обновить',refresh));const runtime=node('details');runtime.append(node('summary','Среда выполнения и проверки'),node('p','Команды выполняются в реальном Sandbox при наличии настроенной среды и разрешения проекта.','context-note'));const command=field('Команда','runtime-command');command.input.placeholder='npm test';const port=field('Порт preview','runtime-port','5173','number');port.input.min='1024';port.input.max='65535';const out=node('pre');out.setAttribute('aria-live','polite');const bar=node('div','','toolbar');let pending:{body:string;key:string}|null=localRead(`pulse.runtime.${accountId}.${id}`,null);for(const [action,title] of [['test','Запустить проверку'],['exec','Выполнить команду'],['preview','Запустить preview']] as const){const b=button(title,async()=>{if(!command.input.value.trim())throw Error('Введите команду.');const body=JSON.stringify({action,command:command.input.value,...(action==='preview'?{port:Number(port.input.value)}:{})});if(pending&&pending.body!==body)throw Error('Предыдущая команда могла быть принята. Повторите её без изменения параметров, чтобы получить результат.');pending??={body,key:crypto.randomUUID()};localWrite(`pulse.runtime.${accountId}.${id}`,pending);out.textContent='Команда отправляется в среду выполнения…';try{const result=await api(`${path}/runtime`,{method:'POST',headers:{'Idempotency-Key':pending.key},body:pending.body});pending=null;localWrite(`pulse.runtime.${accountId}.${id}`,null);if(disposed)return;out.textContent=`${result.available?'Среда доступна':'Среда недоступна'} · exit ${result.exitCode??'неизвестно'}\n${result.output??result.error??''}${action==='test'?`\nПроверка: ${result.tests?.ok===true?'подтверждена':'не подтверждена'}`:''}`;if(result.url){const url=new URL(result.url,location.href);if(url.protocol!=='https:'||url.origin===location.origin)throw Error('Сервер не вернул отдельный защищённый адрес preview.');const link=node('a','Открыть работающий preview ↗','back-link');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';runtime.append(link);}}catch(e){const code=(e as {status?:number}).status;if(code&&[400,401,403,404,409,422,429,503].includes(code)){pending=null;localWrite(`pulse.runtime.${accountId}.${id}`,null);}out.textContent=errorText(e);throw e;}});b.disabled=!writable;bar.append(b);}runtime.append(command.wrap,port.wrap,bar,out);host.append(tools,frame,runtime);void refresh().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;frame.removeAttribute('srcdoc');};
}
