import {type API,button,field,node,status,projectAPI,errorText} from './workbench-common';
type Assignment={id:string;enabled:boolean;connectionIds?:string[];allowedTools?:string[]};
export function mountTools(host:HTMLElement,id:string,api:API,writable:boolean,connections:()=>unknown):()=>void {
 let disposed=false,revision=0;host.dataset.panel='plugins';const message=status(host),list=node('div','','plugin-list');host.append(node('h2','Инструменты проекта'),node('p','Выберите навыки и подключения, которыми агент может пользоваться в этом проекте. Изменения прав действуют на сервере.','muted'),button('Подключить сервис',connections),list);
 const read:Array<()=>Assignment>=[];
 async function load(){const [catalog,configured]=await Promise.all([api('/api/plugins/catalog'),api(`${projectAPI(id)}/plugins`)]);if(disposed)return;revision=configured.revision;list.replaceChildren();read.length=0;
  for(const plugin of catalog.plugins??[]){const existing=(configured.plugins??[]).find((p:Assignment)=>p.id===plugin.id);const card=node('article','','card'),enable=field(plugin.name,`plugin-${plugin.id}`,'','checkbox');enable.input.checked=!!existing?.enabled;enable.input.disabled=!writable;card.append(enable.wrap,node('p',plugin.description),node('small',`Версия ${plugin.version} · ${plugin.kind==='skill'?'Навык':'Подключение'}`));
   const tools=node('div','','plugin-tools'),chosen:Array<{input:HTMLInputElement;id:string}>=[],chosenConnections:Array<{input:HTMLInputElement;id:string}>=[];
   if(plugin.kind==='connector'){for(const connection of (catalog.connections??[]).filter((c:any)=>`mcp:${c.endpointKey}`===plugin.id)){const selection=field(connection.label,`connection-${connection.id}`,'','checkbox');selection.input.checked=!!existing?.connectionIds?.includes(connection.id);selection.input.disabled=!writable;chosenConnections.push({input:selection.input,id:connection.id});tools.append(selection.wrap);for(const tool of connection.tools??[]){if(chosen.some(c=>c.id===tool.name))continue;const select=field(`${tool.name} · ${tool.risk??'права уточняются'}`,`tool-${connection.id}-${tool.name}`,'','checkbox');select.input.checked=!!existing?.allowedTools?.includes(tool.name);select.input.disabled=!writable;select.input.title=tool.description;chosen.push({input:select.input,id:tool.name});tools.append(select.wrap);}}if(!chosenConnections.length)tools.append(node('p','Сначала подключите сервис и проверьте соединение.','muted'));}
   else for(const name of plugin.tools??[]){const select=field(name,`tool-${plugin.id}-${name}`,'','checkbox');select.input.checked=existing?.allowedTools?existing.allowedTools.includes(name):true;select.input.disabled=!writable;chosen.push({input:select.input,id:name});tools.append(select.wrap);}
   const details=node('details');details.append(node('summary','Разрешённые инструменты'),tools);card.append(details);list.append(card);read.push(()=>({id:plugin.id,enabled:enable.input.checked,allowedTools:chosen.filter(c=>c.input.checked).map(c=>c.id),...(plugin.kind==='connector'?{connectionIds:chosenConnections.filter(c=>c.input.checked).map(c=>c.id)}:{})}));
  }save.disabled=!writable;message.textContent=configured.configured?'Права проекта загружены.':'Настройки проекта ещё не заданы. Сохраните явный набор разрешений.';
 }
 const save=button('Сохранить права',async()=>{const result=await api(`${projectAPI(id)}/plugins`,{method:'PUT',body:JSON.stringify({baseRevision:revision,plugins:read.map(r=>r())})});if(disposed)return;revision=result.revision;message.textContent='Права проекта сохранены.';},'primary');save.disabled=true;host.append(save,button('Перечитать настройки',load));void load().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;};
}
export function mountModel(host:HTMLElement,id:string,api:API,writable:boolean):()=>void {
 let disposed=false,revision=0;host.dataset.panel='model';const message=status(host),form=node('div','','settings-grid'),label=node('label','Модель для задач'),select=node('select');select.id='project-model';label.htmlFor=select.id;label.append(select);
 const reasoningLabel=node('label','Глубина рассуждений'),reasoning=node('select');reasoning.id='project-reasoning';reasoningLabel.htmlFor=reasoning.id;for(const value of ['','low','medium','high','xhigh']){const option=node('option',value||'По умолчанию');option.value=value;reasoning.append(option);}reasoningLabel.append(reasoning);
 const iterations=field('Максимум шагов','project-iterations','8','number');iterations.input.min='1';iterations.input.max='40';const budget=field('Лимит задачи, USD','project-budget','','number');budget.input.min='0';budget.input.step='0.01';form.append(label,reasoningLabel,iterations.wrap,budget.wrap);host.append(node('h2','Модель и бюджет'),node('p','Доступность определяется настройками платформы, ключами провайдера и проверенной стоимостью.','muted'),form);
 const details=node('p','','context-note');host.append(details);let models:any[]=[];
 const describe=()=>{const previous=reasoning.value;const model=models.find(m=>(m.id??m.slug)===select.value);reasoning.replaceChildren();for(const value of ['',...(model?.reasoningEfforts??[])]){const option=node('option',value||'По умолчанию');option.value=value;reasoning.append(option);}reasoning.value=[...reasoning.options].some(o=>o.value===previous)?previous:'';reasoning.disabled=!writable||!model?.reasoningEfforts?.length;details.textContent=model?[model.name??model.label??model.id,model.reason??model.unavailableReason??'',model.available===false?'Недоступна для запуска':''].filter(Boolean).join(' · '):'Автоматический выбор из доступных моделей.';};select.onchange=describe;
 async function load(){const [catalog,current]=await Promise.all([api('/api/workbench/models'),api(`${projectAPI(id)}/model`)]);if(disposed)return;revision=current.revision;models=catalog.models??[];select.replaceChildren();const auto=node('option','Автоматически');auto.value='';select.append(auto);for(const model of models){const option=node('option',`${model.name??model.label??model.id??model.slug}${model.available===false?' — недоступна':''}`);option.value=model.id??model.slug;select.append(option);}const settings=current.settings??{};select.value=settings.preferredModel??'';iterations.input.max=String(catalog.configuration?.maxIterations??20);budget.input.max=String(catalog.configuration?.maxCostUsd??1);iterations.input.value=String(settings.maxIterations??catalog.configuration?.defaultIterations??12);budget.input.value=settings.maxCostUsd===undefined?'':String(settings.maxCostUsd);describe();reasoning.value=settings.reasoningEffort??'';save.disabled=!writable;message.textContent='Настройки проекта загружены.';}
 const save=button('Сохранить настройки',async()=>{const settings={...(select.value?{preferredModel:select.value}:{}),...(reasoning.value?{reasoningEffort:reasoning.value}:{}),maxIterations:Number(iterations.input.value),...(budget.input.value?{maxCostUsd:Number(budget.input.value)}:{})};const result=await api(`${projectAPI(id)}/model`,{method:'PUT',body:JSON.stringify({baseRevision:revision,settings})});if(disposed)return;revision=result.revision;message.textContent='Модель и лимиты сохранены для следующих задач.';},'primary');save.disabled=true;for(const field of [select,reasoning,iterations.input,budget.input])field.disabled=!writable;host.append(save);void load().catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;};
}
