import {type API,type Account,type Project,button,field,node,status,projectAPI,errorText} from './workbench-common';
import {mountCode,mountPreview} from './project-code';
import {mountChat,mountMemory,mountVersions} from './project-context';
import {mountTools,mountModel} from './project-tools';
export const workbenchTabs=['task','chat','files','preview','tools','memory','versions','settings'] as const;
export type WorkbenchTab=typeof workbenchTabs[number];
const labels:Record<WorkbenchTab,string>={task:'Задача',chat:'Чат',files:'Файлы',preview:'Предпросмотр',tools:'Инструменты',memory:'Память',versions:'Версии',settings:'Настройки'};
export interface WorkbenchOptions {api:API;account:Account|null;id:string;tab:WorkbenchTab;composer:HTMLElement;mission:HTMLElement;connect:()=>unknown;navigate:(id:string,tab:WorkbenchTab)=>void;onProject:(project:Project)=>void;}
export function mountWorkbench(host:HTMLElement,options:WorkbenchOptions):()=>void {
 const {api,account,id,tab}=options;let disposed=false,cleanup=()=>{};host.replaceChildren();host.dataset.panel='workbench';const header=node('div','','workbench-header'),title=node('h1','Проект'),meta=node('p','','muted');title.tabIndex=-1;const breadcrumb=node('a','← Все проекты','back-link');breadcrumb.href='/projects';header.append(breadcrumb,title,meta);const message=status(host);host.prepend(header);if(!account){message.textContent='Войдите в аккаунт, чтобы открыть проект.';return()=>{disposed=true;};}
 const writable=account.role!=='viewer',nav=node('nav','','workbench-tabs');nav.setAttribute('aria-label','Разделы проекта');for(const key of workbenchTabs){const a=node('a',labels[key]);a.href=`${/^https?:$/.test(location.protocol)?'':'#'}/projects/${encodeURIComponent(id)}/${key}`;a.className=key===tab?'active':'';if(key===tab)a.setAttribute('aria-current','page');a.onclick=e=>{if(e.button||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();options.navigate(id,key);};nav.append(a);}const panel=node('section','','workbench-panel');panel.dataset.panel=tab;host.append(nav,panel);message.textContent='Загружаю проект…';
 void api(projectAPI(id)).then(result=>{if(disposed)return;const project:Project=result.project;options.onProject(project);title.textContent=project.name;meta.textContent=[project.description,project.status==='archived'?'Архив':'Активный проект'].filter(Boolean).join(' · ');message.textContent=writable?'':'Ваш аккаунт разрешает только просмотр.';
  if(tab==='task'){panel.append(node('h2','Что сделать в проекте?'),node('p','Опишите изменение. Агент работает с файлами, инструментами и лимитами этого проекта.','muted'),options.composer,options.mission);}
  if(tab==='chat')cleanup=mountChat(panel,id,account.id,api,writable);
  if(tab==='files')cleanup=mountCode(panel,id,account.id,api,writable);
  if(tab==='preview')cleanup=mountPreview(panel,id,api,writable,account.id);
  if(tab==='tools')cleanup=mountTools(panel,id,api,writable,options.connect);
  if(tab==='memory')cleanup=mountMemory(panel,id,api,writable);
  if(tab==='versions')cleanup=mountVersions(panel,id,api,writable);
  if(tab==='settings'){
   const metadata=node('section');metadata.dataset.panel='metadata';status(metadata);metadata.append(node('h2','О проекте'));const name=field('Название','project-name',project.name),description=field('Описание','project-description',project.description??'');name.input.maxLength=120;description.input.maxLength=2000;metadata.append(name.wrap,description.wrap);const save=button('Сохранить описание',async()=>{const result=await api(projectAPI(id),{method:'PATCH',body:JSON.stringify({baseRevision:project.revision,name:name.input.value,description:description.input.value})});if(disposed)return;Object.assign(project,result.project);title.textContent=project.name;message.textContent='Описание проекта сохранено.';});save.disabled=!writable;const archive=button(project.status==='archived'?'Вернуть из архива':'В архив',async()=>{const result=await api(projectAPI(id),{method:'PATCH',body:JSON.stringify({baseRevision:project.revision,status:project.status==='archived'?'active':'archived'})});if(disposed)return;Object.assign(project,result.project);archive.textContent=project.status==='archived'?'Вернуть из архива':'В архив';meta.textContent=project.status==='archived'?'Архив':'Активный проект';message.textContent='Статус проекта сохранён.';});archive.disabled=!writable;metadata.append(save,archive);const models=node('section','','model-settings');panel.append(metadata,models);cleanup=mountModel(models,id,api,writable);
  }
 }).catch(e=>{if(!disposed)message.textContent=errorText(e);});return()=>{disposed=true;cleanup();};
}
export async function renderProjectHub(host:HTMLElement,artifacts:HTMLElement,api:API,account:Account|null,open:(id:string)=>void,query='',filter='active'):Promise<void>{
 if(!account){host.textContent='Войдите, чтобы увидеть свои проекты.';return;}host.textContent='Загружаю проекты…';const result=await api(`/api/workbench/projects?q=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}`);host.replaceChildren();for(const project of result.projects??[]){const card=node('a','','card project-card');card.href=`/projects/${encodeURIComponent(project.id)}/task`;card.append(node('small',project.status==='archived'?'АРХИВ':'ПРОЕКТ'),node('h3',project.name),node('p',project.description??'Откройте задачи, файлы и инструменты проекта.'),node('span','Открыть пространство ↗','card-action'));card.onclick=e=>{if(e.button||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();open(project.id);};host.append(card);}if(!host.childElementCount)host.append(node('p',query?'По вашему запросу ничего не найдено.':'Первый проект начинается с идеи. Создайте пространство для файлов, переписки и инструментов.','empty-state'));
 if(result.nextCursor){const more=button('Загрузить ещё',async()=>{const next=await api(`/api/workbench/projects?q=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}&cursor=${encodeURIComponent(result.nextCursor)}`);for(const project of next.projects??[]){const card=button(project.name,()=>open(project.id),'card');host.append(card);}result.nextCursor=next.nextCursor;if(!next.nextCursor)more.remove();});host.append(more);}
 artifacts.textContent='Загружаю файлы…';const stored=await api('/api/studio/artifacts?projectId=');artifacts.replaceChildren();for(const artifact of stored.artifacts??[]){const card=node('a',artifact.name,'card');card.href=artifact.url??`/api/studio/artifacts/${encodeURIComponent(artifact.id)}`;card.download=artifact.name;artifacts.append(card);}if(!artifacts.childElementCount)artifacts.append(node('p','Файлы без проекта появятся здесь. Новые результаты студий сохраняются в выбранный проект.','empty-state'));
}
